export const environment = {
  production: true,
  agGridLicenceKey:
    'Using_this_{AG_Grid}_Enterprise_key_{AG-082499}_in_excess_of_the_licence_granted_is_not_permitted___Please_report_misuse_to_legal@ag-grid.com___For_help_with_changing_this_key_please_contact_info@ag-grid.com___{Softone_Applications_AB}_is_granted_a_{Single_Application}_Developer_License_for_the_application_{GO}_only_for_{2}_Front-End_JavaScript_developers___All_Front-End_JavaScript_developers_working_on_{GO}_need_to_be_licensed___{GO}_has_been_granted_a_Deployment_License_Add-on_for_{4}_Production_Environments___This_key_works_with_{AG_Grid}_Enterprise_versions_released_before_{30_June_2026}____[v3]_[01]_MTc4Mjc3NDAwMDAwMA==a715fa866471c7fe37caddc633f81857',
};
