import { ICustomerLedgerSaveDTO } from "../../Scripts/TypeLite.Net4";
import { SoeOriginStatus, TermGroup_BillingType, TermGroup_InvoiceVatType } from "../../Util/CommonEnumerations";

export class CustomerLedgerSaveDTO implements ICustomerLedgerSaveDTO {
    voucherSeriesId: number;
    voucherSeriesTypeId: number;
    originStatus: SoeOriginStatus;
    originDescription: string;
    invoiceId: number;
    billingType: TermGroup_BillingType;
    vatType: TermGroup_InvoiceVatType;
    actorId: number;
    seqNr: number;
    invoiceNr: string;
    ocr: string;
    invoiceDate: Date;
    dueDate: Date;
    voucherDate: Date;
    currencyId: number;
    currencyDate: Date;
    currencyRate: number;
    referenceOur: string;
    referenceYour: string;
    totalAmount: number;
    totalAmountCurrency: number;
    vatAmount: number;
    vatAmountCurrency: number;
    paidAmount: number;
    paidAmountCurrency: number;
    remainingAmount: number;
    fullyPayed: boolean;
    sysPaymentTypeId: number;
    paymentNr: string;
    cashSale: boolean;
    sumAmount: number;
    sumAmountCurrency: number;
    freightAmount: number;
    freightAmountCurrency: number;
    invoiceFee: number;
    invoiceFeeCurrency: number;
    centRounding: number;
    invoiceText: string;
    marginalIncome: number;
    marginalIncomeCurrency: number;
    marginalIncomeRatio: number;
    paymentConditionId: number;
    internalDescription: string;
    vatCodeId: number;
}
