import { IHandleBillingRowDTO } from "../../Scripts/TypeLite.Net4";
import { SoeEntityState, SoeInvoiceRowType, TermGroup_InvoiceProductCalculationType, SoeProductRowType } from "../../Util/CommonEnumerations";
import { CalendarUtility } from "../../Util/CalendarUtility";

export class HandleBillingRowDTO implements IHandleBillingRowDTO {
    actorCustomerId: number;
    amount: number;
    amountCurrency: number;
    attestStateColor: string;
    attestStateId: number;
    attestStateName: string;
    created: Date;
    currencyCode: string;
    currencyId: number;
    customer: string;
    customerInvoiceRowId: number;
    date: Date;
    description: string;
    discountAmount: number;
    discountAmountCurrency: number;
    discountPercent: number;
    discountType: number;
    ediEntryId: number;
    ediTextValue: string;
    householdDeductionType: number;
    invoiceId: number;
    invoiceNr: string;
    invoiceQuantity: number;
    isStockRow: boolean;
    isTimeProjectRow: boolean;
    marginalIncome: number;
    marginalIncomeCurrency: number;
    marginalIncomeLimit: number;
    marginalIncomeRatio: number;
    previouslyInvoicedQuantity: number;
    productCalculationType: TermGroup_InvoiceProductCalculationType;
    productId: number;
    productName: string;
    productNr: string;
    productRowType: SoeProductRowType;
    productUnitCode: string;
    productUnitId: number;
    project: string;
    projectId: number;
    projectNr: string;
    purchasePrice: number;
    purchasePriceCurrency: number;
    quantity: number;
    rowNr: number;
    status: number;
    sumAmount: number;
    sumAmountCurrency: number;
    text: string;
    timeManuallyChanged: boolean;
    type: SoeInvoiceRowType;
    validForInvoice: boolean;
    vatAmount: number;
    vatAmountCurrency: number;
}
