import { IPayrollCalculationProductDTO, IAttestPayrollTransactionDTO, IAttestStateDTO, IAttestTransitionLogDTO, IAccountDimDTO, IAccountDTO, IAccountingSettingsRowDTO } from "../../Scripts/TypeLite.Net4";
import { CalendarUtility } from "../../Util/CalendarUtility";
import { SoeTimePayrollScheduleTransactionType, TermGroup_TimeCodeRegistrationType, SoeTimeCodeType } from "../../Util/CommonEnumerations";

export class PayrollCalculationProductDTO implements IPayrollCalculationProductDTO {
    accountDims: IAccountDimDTO[];
    accountingLongString: string;
    accountingShortString: string;
    accountInternals: IAccountDTO[];
    accountStd: IAccountDTO;
    amount: number;
    amountCurrency: number;
    amountEntCurrency: number;
    attestPayrollTransactions: AttestPayrollTransactionDTO[];
    attestStateColor: string;
    attestStateId: number;
    attestStateName: string;
    attestStates: IAttestStateDTO[];
    attestStateSort: number;
    attestTransitionLogs: IAttestTransitionLogDTO[];
    calenderDayFactor: number;
    dateFrom: Date;
    dateFromString: string;
    dateTo: Date;
    dateToString: string;
    employeeId: number;
    hasAttestStates: boolean;
    hasComment: boolean;
    hasInfo: boolean;
    hasPayrollScheduleTransactions: boolean;
    hasPayrollTransactions: boolean;
    hasSameAttestState: boolean;
    hideDate: boolean;
    hideQuantity: boolean;
    hideUnitprice: boolean;
    includedInPayrollProductChain: boolean;
    isAdded: boolean;
    isAverageCalculated: boolean;
    isBelowEmploymentTaxLimitRuleFromPreviousPeriods: boolean;
    isBelowEmploymentTaxLimitRuleHidden: boolean;
    isCentRounding: boolean;
    isMonthlySalary: boolean;
    isQuantityDays: boolean;
    isQuantityOrFixed: boolean;
    isQuantityRounding: boolean;
    isRetroactive: boolean;
    isRounding: boolean;
    isVacationFiveDaysPerWeek: boolean;
    payrollProductExport: boolean;
    payrollProductFactor: number;
    payrollProductId: number;
    payrollProductName: string;
    payrollProductNumber: string;
    payrollProductNumberSort: string;
    payrollProductPayed: boolean;
    payrollProductShortName: string;
    payrollProductString: string;
    quantity: number;
    quantity_HH_DD_String: string;
    quantityCalendarDays: number;
    quantityString: string;
    quantityWorkDays: number;
    sysPayrollTypeLevel1: number;
    sysPayrollTypeLevel1Name: string;
    sysPayrollTypeLevel2: number;
    sysPayrollTypeLevel2Name: string;
    sysPayrollTypeLevel3: number;
    sysPayrollTypeLevel3Name: string;
    sysPayrollTypeLevel4: number;
    sysPayrollTypeLevel4Name: string;
    timeUnit: number;
    transactionComment: string;
    uniqueId: string;
    unitPrice: number;
    unitPriceCurrency: number;
    unitPriceCurrencyString: string;
    unitPriceEntCurrency: number;
    unitPriceEntCurrencyString: string;
    unitPriceString: string;

    public fixDates() {
        this.dateFrom = CalendarUtility.convertToDate(this.dateFrom);
        this.dateTo = CalendarUtility.convertToDate(this.dateTo);
    }

    public setTypes() {
        if (this.attestPayrollTransactions) {
            this.attestPayrollTransactions = this.attestPayrollTransactions.map(x => {
                let obj = new AttestPayrollTransactionDTO();
                angular.extend(obj, x);
                obj.fixDates();
                return obj;
            });
        } else {
            this.attestPayrollTransactions = [];
        }
    }
}

export class AttestPayrollTransactionDTO implements IAttestPayrollTransactionDTO {
    absenceIntervalNr: number;
    accountDims: IAccountDimDTO[];
    accountingDescription: string;
    accountingLongString: string;
    accountingSettings: IAccountingSettingsRowDTO[];
    accountingShortString: string;
    accountInternalIds: number[];
    accountInternals: IAccountDTO[];
    accountStd: IAccountDTO;
    accountStdId: number;
    addedDateFrom: Date;
    addedDateTo: Date;
    allTimePayrollTransactionIds: number[];
    amount: number;
    amountCurrency: number;
    amountEntCurrency: number;
    attestItemUniqueId: string;
    attestStateColor: string;
    attestStateId: number;
    attestStateInitial: boolean;
    attestStateName: string;
    attestStateSort: number;
    attestTransitionLogs: IAttestTransitionLogDTO[];
    calenderDayFactor: number;
    comment: string;
    commentGrouping: number;
    created: Date;
    createdBy: string;
    date: Date;
    employeeChildId: number;
    employeeChildName: string;
    employeeId: number;
    employeeVehicleId: number;
    formula: string;
    formulaExtracted: string;
    formulaNames: string;
    formulaOrigin: string;
    formulaPlain: string;
    guidId: string;
    guidIdTimeBlock: string;
    guidIdTimeCodeTransaction: string;
    hasAttestState: boolean;
    hasComment: boolean;
    hasInfo: boolean;
    hasSameAttestState: boolean;
    includedInPayrollProductChain: boolean;
    invoiceQuantity: number;
    isAbsence: boolean;
    isAbsenceAbsenceTime: boolean;
    isAdded: boolean;
    isAddedOrFixed: boolean;
    isAdditionOrDeduction: boolean;
    isAverageCalculated: boolean;
    isBelowEmploymentTaxLimitRuleFromPreviousPeriods: boolean;
    isBelowEmploymentTaxLimitRuleHidden: boolean;
    isCentRounding: boolean;
    isDistributed: boolean;
    isEmployeeVehicle: boolean;
    isEmploymentTaxAndHidden: boolean;
    isExported: boolean;
    isFixed: boolean;
    isModified: boolean;
    isPayrollProductChainMainParent: boolean;
    isPayrollStartValue: boolean;
    isPreliminary: boolean;
    isPresence: boolean;
    isPresenceWorkOutsideScheduleTime: boolean;
    isQuantityOrFixed: boolean;
    isQuantityRounding: boolean;
    isRetroactive: boolean;
    isReversed: boolean;
    isRounding: boolean;
    isScheduleTransaction: boolean;
    isSelectDisabled: boolean;
    isSelected: boolean;
    isSpecifiedUnitPrice: boolean;
    isUnionFee: boolean;
    isVacationFiveDaysPerWeek: boolean;
    isVacationReplacement: boolean;
    isVacationYearEnd: boolean;
    manuallyAdded: boolean;
    modified: Date;
    modifiedBy: string;
    noOfAbsenceAbsenceTime: number;
    noOfPresenceWorkOutsideScheduleTime: number;
    parentGuidId: string;
    parentId: number;
    payrollCalculationPerformed: boolean;
    payrollCalculationProductUniqueId: string;
    payrollImportEmployeeTransactionId: number;
    payrollPriceFormulaId: number;
    payrollPriceTypeId: number;
    payrollProductExport: boolean;
    payrollProductFactor: number;
    payrollProductId: number;
    payrollProductName: string;
    payrollProductNumber: string;
    payrollProductPayed: boolean;
    payrollProductShortName: string;
    payrollProductString: string;
    payrollProductSysPayrollTypeLevel1: number;
    payrollProductSysPayrollTypeLevel2: number;
    payrollProductSysPayrollTypeLevel3: number;
    payrollProductSysPayrollTypeLevel4: number;
    payrollProductUseInPayroll: boolean;
    payrollStartValueRowId: number;
    quantity: number;
    quantityCalendarDays: number;
    quantityDays: number;
    quantityString: string;
    quantityWorkDays: number;
    retroactivePayrollOutcomeId: number;
    retroTransactionType: string;
    reversedDate: Date;
    scheduleTransactionType: SoeTimePayrollScheduleTransactionType;
    showEdit: boolean;
    startTime: Date;
    startTimeString: string;
    stopTime: Date;
    stopTimeString: string;
    sysPayrollTypeLevel1: number;
    sysPayrollTypeLevel2: number;
    sysPayrollTypeLevel3: number;
    sysPayrollTypeLevel4: number;
    timeBlockDateId: number;
    timeBlockId: number;
    timeCodeRegistrationType: TermGroup_TimeCodeRegistrationType;
    timeCodeTransactionId: number;
    timeCodeType: SoeTimeCodeType;
    timePayrollTransactionId: number;
    timePeriodId: number;
    timePeriodName: string;
    timeUnit: number;
    transactionSysPayrollTypeLevel1: number;
    transactionSysPayrollTypeLevel2: number;
    transactionSysPayrollTypeLevel3: number;
    transactionSysPayrollTypeLevel4: number;
    unionFeeId: number;
    unitPrice: number;
    unitPriceCurrency: number;
    unitPriceEntCurrency: number;
    unitPriceGrouping: number;
    unitPricePayrollSlipGrouping: number;
    updateChildren: boolean;
    vacationYearEndRowId: number;
    vatAmount: number;
    vatAmountCurrency: number;
    vatAmountEntCurrency: number;

    public fixDates() {
        this.addedDateFrom = CalendarUtility.convertToDate(this.addedDateFrom);
        this.addedDateTo = CalendarUtility.convertToDate(this.addedDateTo);
        this.created = CalendarUtility.convertToDate(this.created);
        this.modified = CalendarUtility.convertToDate(this.modified);
        this.date = CalendarUtility.convertToDate(this.date);
        this.reversedDate = CalendarUtility.convertToDate(this.reversedDate);
        this.startTime = CalendarUtility.convertToDate(this.startTime);
        this.stopTime = CalendarUtility.convertToDate(this.stopTime);
    }
}
