import { ISupplierDTO, IContactAddressItem, IPaymentInformationDTO, IAccountingSettingsRowDTO, IAttestWorkFlowHeadDTO } from "../../Scripts/TypeLite.Net4";
import { TermGroup_InvoiceVatType, SoeEntityState } from "../../Util/CommonEnumerations";

export class SupplierDTO implements ISupplierDTO {
    actorSupplierId: number;
    vatType: TermGroup_InvoiceVatType;
    paymentConditionId: number;
    factoringSupplierId: number;
    currencyId: number;
    deliveryConditionId: number;
    deliveryTypeId: number;
    contactEcomId: number;
    sysCountryId: number;
    sysLanguageId: number;
    vatCodeId: number;
    supplierNr: string;
    name: string;
    orgNr: string;
    vatNr: string;
    invoiceReference: string;
    bic: string;
    ourCustomerNr: string;
    copyInvoiceNrToOcr: boolean;
    interim: boolean;
    manualAccounting: boolean;
    blockPayment: boolean;
    isEDISupplier: boolean;
    riksbanksCode: string;
    created: Date;
    createdBy: string;
    modified: Date;
    modifiedBy: string;
    note: string;
    showNote: boolean;
    state: SoeEntityState;
    ourReference: string;
    sysWholeSellerId: number;
    attestWorkFlowGroupId: number;
    active: boolean;
    consentDate: Date;
    consentModified: Date;
    consentModifiedBy: string;
    isPrivatePerson: boolean;
    hasConsent: boolean;
    intrastatCodeId: number;
    isEUCountryBased: boolean;
    contactAddresses: IContactAddressItem[];
    contactPersons: number[];
    categoryIds: number[];
    paymentInformationForegin: IPaymentInformationDTO;
    paymentInformationDomestic: IPaymentInformationDTO;
    accountingSettings: IAccountingSettingsRowDTO[];
    templateAttestHead: IAttestWorkFlowHeadDTO;
}
