//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
    [System.SerializableAttribute()]
    public partial class AltinnFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnExtendedErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnLocalizedErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnErrorMessage {
            get {
                return this.AltinnErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnErrorMessageField, value) != true)) {
                    this.AltinnErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnExtendedErrorMessage {
            get {
                return this.AltinnExtendedErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnExtendedErrorMessageField, value) != true)) {
                    this.AltinnExtendedErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnExtendedErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnLocalizedErrorMessage {
            get {
                return this.AltinnLocalizedErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnLocalizedErrorMessageField, value) != true)) {
                    this.AltinnLocalizedErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnLocalizedErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorGuid {
            get {
                return this.ErrorGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorGuidField, value) != true)) {
                    this.ErrorGuidField = value;
                    this.RaisePropertyChanged("ErrorGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorID {
            get {
                return this.ErrorIDField;
            }
            set {
                if ((this.ErrorIDField.Equals(value) != true)) {
                    this.ErrorIDField = value;
                    this.RaisePropertyChanged("ErrorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserGuid {
            get {
                return this.UserGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.UserGuidField, value) != true)) {
                    this.UserGuidField = value;
                    this.RaisePropertyChanged("UserGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="LogicalFormSchemaDefinitionBEList", Namespace="http://schemas.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", ItemName="LogicalFormSchemaDefinition")]
    [System.SerializableAttribute()]
    public class LogicalFormSchemaDefinitionBEList : System.Collections.Generic.List<SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.LogicalFormSchemaDefinition> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogicalFormSchemaDefinition", Namespace="http://schemas.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10")]
    [System.SerializableAttribute()]
    public partial class LogicalFormSchemaDefinition : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataFormatIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DataFormatProviderTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DataFormatVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataFormatXsdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LogicalFormIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataFormatID {
            get {
                return this.DataFormatIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DataFormatIDField, value) != true)) {
                    this.DataFormatIDField = value;
                    this.RaisePropertyChanged("DataFormatID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DataFormatProviderTypeID {
            get {
                return this.DataFormatProviderTypeIDField;
            }
            set {
                if ((this.DataFormatProviderTypeIDField.Equals(value) != true)) {
                    this.DataFormatProviderTypeIDField = value;
                    this.RaisePropertyChanged("DataFormatProviderTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DataFormatVersion {
            get {
                return this.DataFormatVersionField;
            }
            set {
                if ((this.DataFormatVersionField.Equals(value) != true)) {
                    this.DataFormatVersionField = value;
                    this.RaisePropertyChanged("DataFormatVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataFormatXsd {
            get {
                return this.DataFormatXsdField;
            }
            set {
                if ((object.ReferenceEquals(this.DataFormatXsdField, value) != true)) {
                    this.DataFormatXsdField = value;
                    this.RaisePropertyChanged("DataFormatXsd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LogicalFormID {
            get {
                return this.LogicalFormIDField;
            }
            set {
                if ((this.LogicalFormIDField.Equals(value) != true)) {
                    this.LogicalFormIDField = value;
                    this.RaisePropertyChanged("LogicalFormID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AvailableServiceBEList", Namespace="http://schemas.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", ItemName="AvailableService")]
    [System.SerializableAttribute()]
    public class AvailableServiceBEList : System.Collections.Generic.List<SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.AvailableService> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvailableService", Namespace="http://schemas.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10")]
    [System.SerializableAttribute()]
    public partial class AvailableService : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BuildPackageVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalServiceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExternalServiceEditionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ServiceEditionVersionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceEditionVersionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceOwnerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceOwnerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ValidFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ValidToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BuildPackageVersion {
            get {
                return this.BuildPackageVersionField;
            }
            set {
                if ((this.BuildPackageVersionField.Equals(value) != true)) {
                    this.BuildPackageVersionField = value;
                    this.RaisePropertyChanged("BuildPackageVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalServiceCode {
            get {
                return this.ExternalServiceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalServiceCodeField, value) != true)) {
                    this.ExternalServiceCodeField = value;
                    this.RaisePropertyChanged("ExternalServiceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExternalServiceEditionCode {
            get {
                return this.ExternalServiceEditionCodeField;
            }
            set {
                if ((this.ExternalServiceEditionCodeField.Equals(value) != true)) {
                    this.ExternalServiceEditionCodeField = value;
                    this.RaisePropertyChanged("ExternalServiceEditionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ServiceEditionVersionId {
            get {
                return this.ServiceEditionVersionIdField;
            }
            set {
                if ((this.ServiceEditionVersionIdField.Equals(value) != true)) {
                    this.ServiceEditionVersionIdField = value;
                    this.RaisePropertyChanged("ServiceEditionVersionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceEditionVersionName {
            get {
                return this.ServiceEditionVersionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceEditionVersionNameField, value) != true)) {
                    this.ServiceEditionVersionNameField = value;
                    this.RaisePropertyChanged("ServiceEditionVersionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceName {
            get {
                return this.ServiceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceNameField, value) != true)) {
                    this.ServiceNameField = value;
                    this.RaisePropertyChanged("ServiceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOwnerCode {
            get {
                return this.ServiceOwnerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOwnerCodeField, value) != true)) {
                    this.ServiceOwnerCodeField = value;
                    this.RaisePropertyChanged("ServiceOwnerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOwnerName {
            get {
                return this.ServiceOwnerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOwnerNameField, value) != true)) {
                    this.ServiceOwnerNameField = value;
                    this.RaisePropertyChanged("ServiceOwnerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ValidFrom {
            get {
                return this.ValidFromField;
            }
            set {
                if ((this.ValidFromField.Equals(value) != true)) {
                    this.ValidFromField = value;
                    this.RaisePropertyChanged("ValidFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ValidTo {
            get {
                return this.ValidToField;
            }
            set {
                if ((this.ValidToField.Equals(value) != true)) {
                    this.ValidToField = value;
                    this.RaisePropertyChanged("ValidTo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AvailableServiceBEV2List", Namespace="http://schemas.altinn.no/services/ServiceEngine/ServiceMetaData/2010/10", ItemName="AvailableServiceV2")]
    [System.SerializableAttribute()]
    public class AvailableServiceBEV2List : System.Collections.Generic.List<SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.AvailableServiceV2> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvailableServiceV2", Namespace="http://schemas.altinn.no/services/ServiceEngine/ServiceMetaData/2010/10")]
    [System.SerializableAttribute()]
    public partial class AvailableServiceV2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BuildPackageVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalServiceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExternalServiceEditionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMatchedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ServiceEditionVersionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceEditionVersionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceOwnerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceOwnerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.ServiceTypeV2 ServiceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ValidFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ValidToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BuildPackageVersion {
            get {
                return this.BuildPackageVersionField;
            }
            set {
                if ((this.BuildPackageVersionField.Equals(value) != true)) {
                    this.BuildPackageVersionField = value;
                    this.RaisePropertyChanged("BuildPackageVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalServiceCode {
            get {
                return this.ExternalServiceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalServiceCodeField, value) != true)) {
                    this.ExternalServiceCodeField = value;
                    this.RaisePropertyChanged("ExternalServiceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExternalServiceEditionCode {
            get {
                return this.ExternalServiceEditionCodeField;
            }
            set {
                if ((this.ExternalServiceEditionCodeField.Equals(value) != true)) {
                    this.ExternalServiceEditionCodeField = value;
                    this.RaisePropertyChanged("ExternalServiceEditionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMatched {
            get {
                return this.IsMatchedField;
            }
            set {
                if ((this.IsMatchedField.Equals(value) != true)) {
                    this.IsMatchedField = value;
                    this.RaisePropertyChanged("IsMatched");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ServiceEditionVersionId {
            get {
                return this.ServiceEditionVersionIdField;
            }
            set {
                if ((this.ServiceEditionVersionIdField.Equals(value) != true)) {
                    this.ServiceEditionVersionIdField = value;
                    this.RaisePropertyChanged("ServiceEditionVersionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceEditionVersionName {
            get {
                return this.ServiceEditionVersionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceEditionVersionNameField, value) != true)) {
                    this.ServiceEditionVersionNameField = value;
                    this.RaisePropertyChanged("ServiceEditionVersionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceName {
            get {
                return this.ServiceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceNameField, value) != true)) {
                    this.ServiceNameField = value;
                    this.RaisePropertyChanged("ServiceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOwnerCode {
            get {
                return this.ServiceOwnerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOwnerCodeField, value) != true)) {
                    this.ServiceOwnerCodeField = value;
                    this.RaisePropertyChanged("ServiceOwnerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOwnerName {
            get {
                return this.ServiceOwnerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOwnerNameField, value) != true)) {
                    this.ServiceOwnerNameField = value;
                    this.RaisePropertyChanged("ServiceOwnerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.ServiceTypeV2 ServiceType {
            get {
                return this.ServiceTypeField;
            }
            set {
                if ((this.ServiceTypeField.Equals(value) != true)) {
                    this.ServiceTypeField = value;
                    this.RaisePropertyChanged("ServiceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ValidFrom {
            get {
                return this.ValidFromField;
            }
            set {
                if ((this.ValidFromField.Equals(value) != true)) {
                    this.ValidFromField = value;
                    this.RaisePropertyChanged("ValidFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ValidTo {
            get {
                return this.ValidToField;
            }
            set {
                if ((this.ValidToField.Equals(value) != true)) {
                    this.ValidToField = value;
                    this.RaisePropertyChanged("ValidTo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceTypeV2", Namespace="http://schemas.altinn.no/ServiceDevelopment/Service/2010/10")]
    public enum ServiceTypeV2 : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Correspondence = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reporting = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Collaboration = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Lookup = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CodeList", Namespace="http://schemas.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10")]
    [System.SerializableAttribute()]
    public partial class CodeList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeListIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeListNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.CodeRowBEList CodeListRowsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeListVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LanguageTypeIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodeListID {
            get {
                return this.CodeListIDField;
            }
            set {
                if ((this.CodeListIDField.Equals(value) != true)) {
                    this.CodeListIDField = value;
                    this.RaisePropertyChanged("CodeListID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeListName {
            get {
                return this.CodeListNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeListNameField, value) != true)) {
                    this.CodeListNameField = value;
                    this.RaisePropertyChanged("CodeListName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.CodeRowBEList CodeListRows {
            get {
                return this.CodeListRowsField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeListRowsField, value) != true)) {
                    this.CodeListRowsField = value;
                    this.RaisePropertyChanged("CodeListRows");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodeListVersion {
            get {
                return this.CodeListVersionField;
            }
            set {
                if ((this.CodeListVersionField.Equals(value) != true)) {
                    this.CodeListVersionField = value;
                    this.RaisePropertyChanged("CodeListVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LanguageTypeID {
            get {
                return this.LanguageTypeIDField;
            }
            set {
                if ((this.LanguageTypeIDField.Equals(value) != true)) {
                    this.LanguageTypeIDField = value;
                    this.RaisePropertyChanged("LanguageTypeID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="CodeRowBEList", Namespace="http://schemas.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", ItemName="CodeListRow")]
    [System.SerializableAttribute()]
    public class CodeRowBEList : System.Collections.Generic.List<SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.CodeListRow> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CodeListRow", Namespace="http://schemas.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10")]
    [System.SerializableAttribute()]
    public partial class CodeListRow : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Value1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Value2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Value3Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value1 {
            get {
                return this.Value1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Value1Field, value) != true)) {
                    this.Value1Field = value;
                    this.RaisePropertyChanged("Value1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value2 {
            get {
                return this.Value2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Value2Field, value) != true)) {
                    this.Value2Field = value;
                    this.RaisePropertyChanged("Value2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value3 {
            get {
                return this.Value3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Value3Field, value) != true)) {
                    this.Value3Field = value;
                    this.RaisePropertyChanged("Value3");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilterMatchType", Namespace="http://schemas.altinn.no/serviceengine/formsengine/2009/10")]
    public enum FilterMatchType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DEFAULT = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EXACT = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        STARTSWITH = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ENDSWITH = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CONTAINS = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", ConfigurationName="Altinn.ServiceMetaDataExternal.IServiceMetaDataExternal")]
    public interface IServiceMetaDataExternal {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test", ReplyAction="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.AltinnFault), Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.TestResponse Test(SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10/IServiceMetaD" +
            "ataExternal/GetSchemaDefinitionsForFormTask", ReplyAction="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10/IServiceMetaD" +
            "ataExternal/GetSchemaDefinitionsForFormTaskResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.AltinnFault), Action="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10/IServiceMetaD" +
            "ataExternal/GetSchemaDefinitionsForFormTaskAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.GetSchemaDefinitionsForFormTaskResponse GetSchemaDefinitionsForFormTask(SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.GetSchemaDefinitionsForFormTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10/IServiceMetaD" +
            "ataExternal/GetAvailableServices", ReplyAction="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10/IServiceMetaD" +
            "ataExternal/GetAvailableServicesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.AltinnFault), Action="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10/IServiceMetaD" +
            "ataExternal/GetAvailableServicesAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.GetAvailableServicesResponse GetAvailableServices(SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.GetAvailableServicesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10/IServiceMetaD" +
            "ataExternal/GetAvailableServicesV2", ReplyAction="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10/IServiceMetaD" +
            "ataExternal/GetAvailableServicesV2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.AltinnFault), Action="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10/IServiceMetaD" +
            "ataExternal/GetAvailableServicesV2AltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.GetAvailableServicesV2Response GetAvailableServicesV2(SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.GetAvailableServicesV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10/IServiceMetaD" +
            "ataExternal/GetCodeList", ReplyAction="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10/IServiceMetaD" +
            "ataExternal/GetCodeListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.AltinnFault), Action="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10/IServiceMetaD" +
            "ataExternal/GetCodeListAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.GetCodeListResponse GetCodeList(SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.GetCodeListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10/IServiceMetaD" +
            "ataExternal/GetFilteredCodeList", ReplyAction="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10/IServiceMetaD" +
            "ataExternal/GetFilteredCodeListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.AltinnFault), Action="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10/IServiceMetaD" +
            "ataExternal/GetFilteredCodeListAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.GetFilteredCodeListResponse GetFilteredCodeList(SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.GetFilteredCodeListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestRequest {
        
        public TestRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestResponse", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestResponse {
        
        public TestResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSchemaDefinitionsForFormTask", WrapperNamespace="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", IsWrapped=true)]
    public partial class GetSchemaDefinitionsForFormTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", Order=0)]
        public string externalServiceCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", Order=1)]
        public int externalServiceEditionCode;
        
        public GetSchemaDefinitionsForFormTaskRequest() {
        }
        
        public GetSchemaDefinitionsForFormTaskRequest(string externalServiceCode, int externalServiceEditionCode) {
            this.externalServiceCode = externalServiceCode;
            this.externalServiceEditionCode = externalServiceEditionCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSchemaDefinitionsForFormTaskResponse", WrapperNamespace="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", IsWrapped=true)]
    public partial class GetSchemaDefinitionsForFormTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", Order=0)]
        public SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.LogicalFormSchemaDefinitionBEList GetSchemaDefinitionsForFormTaskResult;
        
        public GetSchemaDefinitionsForFormTaskResponse() {
        }
        
        public GetSchemaDefinitionsForFormTaskResponse(SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.LogicalFormSchemaDefinitionBEList GetSchemaDefinitionsForFormTaskResult) {
            this.GetSchemaDefinitionsForFormTaskResult = GetSchemaDefinitionsForFormTaskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAvailableServices", WrapperNamespace="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", IsWrapped=true)]
    public partial class GetAvailableServicesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", Order=0)]
        public int languageID;
        
        public GetAvailableServicesRequest() {
        }
        
        public GetAvailableServicesRequest(int languageID) {
            this.languageID = languageID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAvailableServicesResponse", WrapperNamespace="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", IsWrapped=true)]
    public partial class GetAvailableServicesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", Order=0)]
        public SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.AvailableServiceBEList GetAvailableServicesResult;
        
        public GetAvailableServicesResponse() {
        }
        
        public GetAvailableServicesResponse(SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.AvailableServiceBEList GetAvailableServicesResult) {
            this.GetAvailableServicesResult = GetAvailableServicesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAvailableServicesV2", WrapperNamespace="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", IsWrapped=true)]
    public partial class GetAvailableServicesV2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", Order=0)]
        public int languageID;
        
        public GetAvailableServicesV2Request() {
        }
        
        public GetAvailableServicesV2Request(int languageID) {
            this.languageID = languageID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAvailableServicesV2Response", WrapperNamespace="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", IsWrapped=true)]
    public partial class GetAvailableServicesV2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", Order=0)]
        public SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.AvailableServiceBEV2List GetAvailableServicesV2Result;
        
        public GetAvailableServicesV2Response() {
        }
        
        public GetAvailableServicesV2Response(SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.AvailableServiceBEV2List GetAvailableServicesV2Result) {
            this.GetAvailableServicesV2Result = GetAvailableServicesV2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCodeList", WrapperNamespace="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", IsWrapped=true)]
    public partial class GetCodeListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", Order=0)]
        public string codeListName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", Order=1)]
        public int codeListVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", Order=2)]
        public int languageID;
        
        public GetCodeListRequest() {
        }
        
        public GetCodeListRequest(string codeListName, int codeListVersion, int languageID) {
            this.codeListName = codeListName;
            this.codeListVersion = codeListVersion;
            this.languageID = languageID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCodeListResponse", WrapperNamespace="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", IsWrapped=true)]
    public partial class GetCodeListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", Order=0)]
        public SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.CodeList GetCodeListResult;
        
        public GetCodeListResponse() {
        }
        
        public GetCodeListResponse(SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.CodeList GetCodeListResult) {
            this.GetCodeListResult = GetCodeListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFilteredCodeList", WrapperNamespace="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", IsWrapped=true)]
    public partial class GetFilteredCodeListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", Order=0)]
        public string codeListName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", Order=1)]
        public int codeListVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", Order=2)]
        public int languageID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", Order=3)]
        public string code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", Order=4)]
        public string value1Filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", Order=5)]
        public string value2Filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", Order=6)]
        public string value3Filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", Order=7)]
        public SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.FilterMatchType filterMatchType;
        
        public GetFilteredCodeListRequest() {
        }
        
        public GetFilteredCodeListRequest(string codeListName, int codeListVersion, int languageID, string code, string value1Filter, string value2Filter, string value3Filter, SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.FilterMatchType filterMatchType) {
            this.codeListName = codeListName;
            this.codeListVersion = codeListVersion;
            this.languageID = languageID;
            this.code = code;
            this.value1Filter = value1Filter;
            this.value2Filter = value2Filter;
            this.value3Filter = value3Filter;
            this.filterMatchType = filterMatchType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFilteredCodeListResponse", WrapperNamespace="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", IsWrapped=true)]
    public partial class GetFilteredCodeListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/ServiceMetaData/2009/10", Order=0)]
        public SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.CodeList GetFilteredCodeListResult;
        
        public GetFilteredCodeListResponse() {
        }
        
        public GetFilteredCodeListResponse(SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.CodeList GetFilteredCodeListResult) {
            this.GetFilteredCodeListResult = GetFilteredCodeListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceMetaDataExternalChannel : SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.IServiceMetaDataExternal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceMetaDataExternalClient : System.ServiceModel.ClientBase<SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.IServiceMetaDataExternal>, SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.IServiceMetaDataExternal {
        
        public ServiceMetaDataExternalClient() {
        }
        
        public ServiceMetaDataExternalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceMetaDataExternalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceMetaDataExternalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceMetaDataExternalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.TestResponse Test(SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        public SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.GetSchemaDefinitionsForFormTaskResponse GetSchemaDefinitionsForFormTask(SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.GetSchemaDefinitionsForFormTaskRequest request) {
            return base.Channel.GetSchemaDefinitionsForFormTask(request);
        }
        
        public SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.GetAvailableServicesResponse GetAvailableServices(SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.GetAvailableServicesRequest request) {
            return base.Channel.GetAvailableServices(request);
        }
        
        public SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.GetAvailableServicesV2Response GetAvailableServicesV2(SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.GetAvailableServicesV2Request request) {
            return base.Channel.GetAvailableServicesV2(request);
        }
        
        public SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.GetCodeListResponse GetCodeList(SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.GetCodeListRequest request) {
            return base.Channel.GetCodeList(request);
        }
        
        public SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.GetFilteredCodeListResponse GetFilteredCodeList(SoftOne.Soe.Business.Altinn.ServiceMetaDataExternal.GetFilteredCodeListRequest request) {
            return base.Channel.GetFilteredCodeList(request);
        }
    }
}
