import { test } from '../../fixtures/sales-fixture';
import * as allure from "allure-js-commons";
import { getAccountExValue, getEnvironmentValue } from '../../../utils/properties';
import { StockUtils } from '../../../apis/utils/StockUtils';

let testCaseId: string = '115139';
let envUrl: string;
let productNumber: string = `${Math.floor(100 + Math.random() * 900)}_${testCaseId}`;
let productName: string = `AutoProduct_${Math.random().toString(36).substring(2, 7)}_${testCaseId}`;
let customer: string = getEnvironmentValue('default_customerStock') ?? '';
let stockUtils: StockUtils;

test.use({ account: { domain: process.env.defualt_domain!, user: 'adminERP' } });

test.beforeEach(async ({ accountEx, salesBasePage, page }) => {
    await allure.parentSuite("Sales");
    await allure.suite("Stock");
    await allure.subSuite("Stock");
    await allure.link('https://dev.azure.com/softonedev/XE/_workitems/edit/' + testCaseId, "Test case : " + testCaseId);
    envUrl = accountEx.baseUrl;
    stockUtils = new StockUtils(page, envUrl);
    await stockUtils.addProductForStatistics(productNumber, productName);
    await salesBasePage.SetupSales(envUrl, getAccountExValue(accountEx, 'role')?.toString() ?? 'Admin');
});

test(testCaseId + ': Integration of product statistics with orders, invoices and balance updates : SR', { tag: ['@Sales', '@Stock', '@Regression'] }, async ({ productsPageJS, orderPageJS, balancePage, invoicePageJS, paymentPage }) => {
    await balancePage.goToMenu('Stock', 'Balance');
    await balancePage.waitforPageLoad();
    await balancePage.filterByProductNumber(productNumber);
    await balancePage.edit(0);
    await balancePage.addQuantity('90');
    await balancePage.saveBalance();
    await orderPageJS.goToMenu('Order', 'Order');
    await orderPageJS.waitForPageLoad();
    await orderPageJS.createItem();
    await orderPageJS.addCustomer(customer);
    await orderPageJS.expandProducts();
    await orderPageJS.addProduct(productNumber);
    await orderPageJS.addColumnToProductRows('Purchase Price');
    await orderPageJS.verifyProductPurchasePrice('140', 0);
    await orderPageJS.saveOrder();
    const orderNumber = await orderPageJS.getOrderNumber();
    await productsPageJS.goToMenu('Product', 'Products');
    await productsPageJS.waitForPageLoad();
    await productsPageJS.filterProductNo(productNumber);
    await productsPageJS.edit();
    await productsPageJS.expandStatistics();
    await productsPageJS.selectTypeInStatistics('Order');
    await productsPageJS.clickSearchInStatistics();
    await productsPageJS.verifyInvoiceNumberInStatistics(orderNumber);
    await balancePage.goToMenu('Stock', 'Balance');
    await balancePage.waitforPageLoad();
    await balancePage.filterByProductNumber(productNumber);
    await balancePage.clickRecalculateBalance();
    await balancePage.verifyInStockInBalanceGrid('90.00');
    await balancePage.verifyInOrderInBalanceGrid('1.00');
    await orderPageJS.goToMenu('Order', 'Order');
    await orderPageJS.waitForPageLoad();
    await orderPageJS.filterByOrderNo(orderNumber);
    await orderPageJS.editOrder();
    await orderPageJS.expandProducts();
    await orderPageJS.addToKlar();
    await orderPageJS.tranferToPreliminaryInvoice();
    await balancePage.goToMenu('Stock', 'Balance');
    await balancePage.waitforPageLoad();
    await balancePage.filterByProductNumber(productNumber);
    await balancePage.clickRecalculateBalance();
    await balancePage.verifyInStockInBalanceGrid('90.00');
    await balancePage.verifyReservedInBalanceGrid('1.00');
    await invoicePageJS.goToMenu('Invoice', 'Invoices');
    await invoicePageJS.filterByOrderNumber(orderNumber);
    await invoicePageJS.editInvoice();
    await invoicePageJS.makeFinalInvoice();
    const invoiceNumber = await invoicePageJS.getInvoiceNumber();
    await balancePage.goToMenu('Stock', 'Balance');
    await balancePage.waitforPageLoad();
    await balancePage.filterByProductNumber(productNumber);
    await balancePage.clickRecalculateBalance();
    await balancePage.verifyReservedInBalanceGrid('0.00');
    await balancePage.verifyInStockInBalanceGrid('89.00');
    await paymentPage.goToMenu('Invoice', 'Payments');
    await paymentPage.waitForPageLoad();
    await paymentPage.filterByInvoiceNumber(invoiceNumber);
    await paymentPage.selectFirstGridRow();
    await paymentPage.fillPaymentDate();
    await paymentPage.clickCreatePayment();
    await balancePage.goToMenu('Stock', 'Balance');
    await balancePage.waitforPageLoad();
    await balancePage.filterByProductNumber(productNumber);
    await balancePage.clickRecalculateBalance();
    await balancePage.verifyReservedInBalanceGrid('0.00');
    await balancePage.verifyInStockInBalanceGrid('89.00');
    await productsPageJS.goToMenu('Product', 'Products');
    await productsPageJS.waitForPageLoad();
    await productsPageJS.filterProductNo(productNumber);
    await productsPageJS.edit();
    await productsPageJS.expandStatistics();
    await productsPageJS.selectTypeInStatistics('Customer invoice');
    await productsPageJS.clickSearchInStatistics();
    await productsPageJS.verifyInvoiceNumberInStatistics(invoiceNumber);
});
