import { test } from '../../fixtures/sales-fixture';
import * as allure from "allure-js-commons";
import { getAccountExValue } from '../../../utils/properties';


let testCaseId: string = '115138';
let envUrl: string;
let productNumber: string = `${Math.floor(100 + Math.random() * 900)}_${testCaseId}`;
let productName: string = `AutoProduct_${Math.random().toString(36).substring(2, 7)}_${testCaseId}`;

test.use({ account: { domain: process.env.defualt_domain!, user: 'adminERP' } });

test.beforeEach(async ({ accountEx, salesBasePage }) => {
    await allure.parentSuite("Sales");
    await allure.suite("Stock");
    await allure.subSuite("Stock");
    await allure.link('https://dev.azure.com/softonedev/XE/_workitems/edit/' + testCaseId, "Test case : " + testCaseId);
    envUrl = accountEx.baseUrl;
    await salesBasePage.SetupSales(envUrl, getAccountExValue(accountEx, 'role')?.toString() ?? 'Admin');
});

test(testCaseId + ': Calculation type for gross margin : SR', { tag: ['@Sales', '@Stock', '@Regression'] }, async ({ productSettingsPage, productsPageJS, balancePage }) => {
    await productSettingsPage.goToMenu('Settings_Sales', 'Settings', true, 'Products');
    await productSettingsPage.waitForPageLoad();
    await productSettingsPage.verifyGrossMarginSettings("Purchase price");
    await productsPageJS.goToMenu('Product', 'Products');
    await productsPageJS.waitForPageLoad();
    await productsPageJS.createItem();
    await productsPageJS.waitforCreateProductPageLoad();
    await productsPageJS.setProductNumber(productNumber);
    await productsPageJS.setProductName(productName);
    await productsPageJS.verifyGrossMarginMethod("");
    await productsPageJS.saveProduct();
    await productsPageJS.closeTab();
    await productsPageJS.filterProductNo(productNumber);
    await productsPageJS.edit();
    await productsPageJS.verifyProductIsActive();
    await productsPageJS.expandPrice();
    await productsPageJS.setPurchasePrice("150");
    await productsPageJS.expandStock();
    await productsPageJS.clickAddRowInStock();
    await productsPageJS.setAveragePrice('140');
    await productsPageJS.setOrderpoint('50');
    await productsPageJS.saveProduct();
    await balancePage.goToMenu('Stock', 'Balance');
    await balancePage.waitforPageLoad();
    await balancePage.createItem();
    await balancePage.setProductNumber(productNumber);
    await balancePage.setWarehouseLocation('Main Warehouse');
    await balancePage.addQuantity('5'); 
    await balancePage.verifySetPriceInBalance('150.00');
    await balancePage.handleWarningPopupIfPresent();
    await balancePage.clickAddButtonBalance();
    await productSettingsPage.goToMenu('Settings_Sales', 'Settings', true, 'Products');
    await productSettingsPage.waitForPageLoad();
    await productSettingsPage.setGrossMarginSettings("Average price");
    await balancePage.goToMenu('Stock', 'Balance');
    await balancePage.waitforPageLoad();
    await balancePage.createItem();
    await balancePage.setProductNumber(productNumber);
    await balancePage.handleWarningPopupIfPresent();
    await balancePage.setWarehouseLocation('Main Warehouse');
    await balancePage.addQuantity('5'); 
    await balancePage.verifySetPriceInBalance('140.00');
    await balancePage.clickAddButtonBalance();
    await productSettingsPage.goToMenu('Settings_Sales', 'Settings', true, 'Products');
    await productSettingsPage.waitForPageLoad();
    await productSettingsPage.setGrossMarginSettings("Purchase price");
    await productsPageJS.goToMenu('Product', 'Products');
    await productsPageJS.waitForPageLoad();
    await productsPageJS.filterProductNo(productNumber);
    await productsPageJS.edit();
    await productsPageJS.waitforCreateProductPageLoad();
    await productsPageJS.setGrossMarginMethod("Average price");
    await productsPageJS.saveProduct();
    await balancePage.goToMenu('Stock', 'Balance');
    await balancePage.waitforPageLoad();
    await balancePage.createItem();
    await balancePage.setProductNumber(productNumber);
    await balancePage.handleWarningPopupIfPresent();
    await balancePage.setWarehouseLocation('Main Warehouse');
    await balancePage.addQuantity('5'); 
    await balancePage.verifySetPriceInBalance('140.00');
    await balancePage.clickAddButtonBalance();
    await productsPageJS.goToMenu('Product', 'Products');
    await productsPageJS.waitForPageLoad();
    await productsPageJS.filterProductNo(productNumber);
    await productsPageJS.edit();
    await productsPageJS.waitforCreateProductPageLoad();
    await productsPageJS.setGrossMarginMethod("Purchase price");
    await productsPageJS.saveProduct();
    await balancePage.goToMenu('Stock', 'Balance');
    await balancePage.waitforPageLoad();
    await balancePage.createItem();
    await balancePage.setProductNumber(productNumber);
    await balancePage.handleWarningPopupIfPresent();
    await balancePage.setWarehouseLocation('Main Warehouse');
    await balancePage.addQuantity('5'); 
    await balancePage.verifySetPriceInBalance('150.00');
    await balancePage.clickAddButtonBalance();
});


