
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface IAccountingSettingDTO {
        type: number;
        dimNr: number;
        dimName: string;
        account1Id: number;
        account1Nr: string;
        account1Name: string;
        account2Id: number;
        account2Nr: string;
        account2Name: string;
        account3Id: number;
        account3Nr: string;
        account3Name: string;
        account4Id: number;
        account4Nr: string;
        account4Name: string;
        account5Id: number;
        account5Nr: string;
        account5Name: string;
        account6Id: number;
        account6Nr: string;
        account6Name: string;
        account7Id: number;
        account7Nr: string;
        account7Name: string;
        account8Id: number;
        account8Nr: string;
        account8Name: string;
        account9Id: number;
        account9Nr: string;
        account9Name: string;
        account10Id: number;
        account10Nr: string;
        account10Name: string;
        percent1: number;
        percent2: number;
        percent3: number;
        percent4: number;
        percent5: number;
        percent6: number;
        percent7: number;
        percent8: number;
        percent9: number;
        percent10: number;
    }

    

    






