
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface IActionResult {
        success: boolean;
        successNumber: number;
        errorNumber: number;
        errorMessage: string;
        infoMessage: string;
        canUserOverride: boolean;
        integerValue: number;
        integerValue2: number;
        decimalValue: number;
        stringValue: string;
        booleanValue: boolean;
        booleanValue2: boolean;
        dateTimeValue: Date;
        value: any;
        value2: any;
        dates: Date[];
        keys: number[];
        strings: string[];
        idDict: { [key: number]: number; };
        intDict: { [key: number]: number; };
        intDict2: { [key: number]: number; };
        strDict: { [key: number]: string; };
        strDict2: { [key: string]: number; };
        strIntListDict: { [key: string]: number[]; };
        objectsAffected: number;
        stackTrace: string;
        exception: any;
        modified: Date;
        modifiedBy: string;
    }

    

    






