
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.






export enum ApiMatrixSelectionType { 
    Unknown = 0,
    Employee = 1,
    DateRange = 2,
    Date = 3,
    IdList = 4,
    Id = 5,
    Bool = 6,
    PayrollProduct = 7,
    Text = 8
}



