
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface IAttestPayrollTransactionDTO {
        guidId: string;
        parentGuidId: string;
        guidIdTimeBlock: string;
        guidIdTimeCodeTransaction: string;
        attestItemUniqueId: string;
        payrollCalculationProductUniqueId: string;
        employeeId: number;
        timePayrollTransactionId: number;
        allTimePayrollTransactionIds: number[];
        unitPrice?: number;
        unitPriceCurrency?: number;
        unitPriceEntCurrency?: number;
        unitPriceGrouping?: number;
        unitPricePayrollSlipGrouping?: number;
        commentGrouping: number;
        amount?: number;
        amountCurrency?: number;
        amountEntCurrency?: number;
        vatAmount?: number;
        vatAmountCurrency?: number;
        vatAmountEntCurrency?: number;
        quantity: number;
        quantityString: string;
        isQuantityOrFixed: boolean;
        reversedDate?: Date;
        isReversed: boolean;
        isPreliminary: boolean;
        isExported: boolean;
        isEmploymentTaxAndHidden: boolean;
        isBelowEmploymentTaxLimitRuleHidden: boolean;
        isBelowEmploymentTaxLimitRuleFromPreviousPeriods: boolean;
        manuallyAdded: boolean;
        comment: string;
        hasComment: boolean;
        hasInfo: boolean;
        addedDateFrom?: Date;
        addedDateTo?: Date;
        isAdded: boolean;
        isFixed: boolean;
        isCentRounding: boolean;
        isQuantityRounding: boolean;
        isSpecifiedUnitPrice: boolean;
        isAdditionOrDeduction: boolean;
        isVacationReplacement: boolean;
        isAddedOrFixed: boolean;
        isRounding: boolean;
        showEdit: boolean;
        isPayrollProductChainMainParent: boolean;
        includedInPayrollProductChain: boolean;
        updateChildren: boolean;
        parentId?: number;
        unionFeeId?: number;
        isUnionFee: boolean;
        employeeVehicleId?: number;
        isEmployeeVehicle: boolean;
        earningTimeAccumulatorId?: number;
        employeeChildId?: number;
        employeeChildName: string;
        payrollStartValueRowId?: number;
        isPayrollStartValue: boolean;
        retroactivePayrollOutcomeId?: number;
        isRetroactive: boolean;
        vacationYearEndRowId?: number;
        isVacationYearEnd: boolean;
        isVacationFiveDaysPerWeek: boolean;
        transactionSysPayrollTypeLevel1?: number;
        transactionSysPayrollTypeLevel2?: number;
        transactionSysPayrollTypeLevel3?: number;
        transactionSysPayrollTypeLevel4?: number;
        absenceIntervalNr: number;
        created?: Date;
        createdBy: string;
        modified?: Date;
        modifiedBy: string;
        payrollPriceFormulaId?: number;
        payrollPriceTypeId?: number;
        formula: string;
        formulaPlain: string;
        formulaExtracted: string;
        formulaNames: string;
        formulaOrigin: string;
        payrollCalculationPerformed?: boolean;
        isDistributed: boolean;
        isAverageCalculated: boolean;
        timeUnit: number;
        quantityWorkDays: number;
        quantityCalendarDays: number;
        calenderDayFactor: number;
        quantityDays: number;
        scheduleTransactionType: SoeTimePayrollScheduleTransactionType;
        isScheduleTransaction: boolean;
        payrollProductId: number;
        payrollProductNumber: string;
        payrollProductName: string;
        payrollProductString: string;
        payrollProductShortName: string;
        payrollProductFactor: number;
        payrollProductPayed: boolean;
        payrollProductExport: boolean;
        payrollProductUseInPayroll: boolean;
        payrollProductSysPayrollTypeLevel1?: number;
        payrollProductSysPayrollTypeLevel2?: number;
        payrollProductSysPayrollTypeLevel3?: number;
        payrollProductSysPayrollTypeLevel4?: number;
        timeCodeTransactionId?: number;
        startTime?: Date;
        startTimeString: string;
        stopTime?: Date;
        stopTimeString: string;
        timeCodeType: SoeTimeCodeType;
        timeCodeRegistrationType: TermGroup_TimeCodeRegistrationType;
        noOfPresenceWorkOutsideScheduleTime?: number;
        isPresenceWorkOutsideScheduleTime: boolean;
        noOfAbsenceAbsenceTime?: number;
        isAbsenceAbsenceTime: boolean;
        timeBlockDateId: number;
        date: Date;
        timeBlockId?: number;
        attestStateId: number;
        attestStateName: string;
        attestStateColor: string;
        attestStateInitial: boolean;
        attestStateSort: number;
        hasSameAttestState: boolean;
        hasAttestState: boolean;
        attestTransitionLogs: IAttestTransitionLogDTO[];
        accountDims: IAccountDimDTO[];
        accountStd: IAccountDTO;
        accountInternals: IAccountDTO[];
        accountingShortString: string;
        accountingLongString: string;
        accountingSettings: IAccountingSettingsRowDTO[];
        accountingDescription: string;
        accountStdId: number;
        accountInternalIds: number[];
        timePeriodId?: number;
        timePeriodName: string;
        retroTransactionType: string;
        invoiceQuantity?: number;
        isModified: boolean;
        isSelected: boolean;
        isSelectDisabled: boolean;
        isPresence: boolean;
        isAbsence: boolean;
        payrollImportEmployeeTransactionId?: number;
        productId: number;
        sysPayrollTypeLevel1?: number;
        sysPayrollTypeLevel2?: number;
        sysPayrollTypeLevel3?: number;
        sysPayrollTypeLevel4?: number;
    }

    

    

    export interface IAttestTransitionLogDTO {
        attestTransitionLogId?: number;
        timePayrollTransactionId: number;
        attestTransitionDate: Date;
        attestStateFromName: string;
        attestStateToName: string;
        attestTransitionUserId: number;
        attestTransitionUserName: string;
        attestTransitionCreatedBySupport: boolean;
    }

    

    

    export interface ISaveAttestTransactionsValidationDTO {
        success: boolean;
        canOverride: boolean;
        title: string;
        message: string;
        validItems: ISaveAttestTransactionDTO[];
    }

    

    

    export interface ISaveAttestTransactionDTO {
        originalUniqueId: string;
        employeeId: number;
        date: Date;
        timePayrollTransactionIds: number[];
    }

    

    






import { SoeTimePayrollScheduleTransactionType, SoeTimeCodeType, TermGroup_TimeCodeRegistrationType } from "../generated-interfaces/Enumerations";
import { IAccountDTO, IAccountingSettingsRowDTO, IAccountDimDTO } from "../generated-interfaces/SOECompModelDTOs";
