
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface IAuthorizeRequestDTO {
        permissionType: TermGroup_SignatoryContractPermissionType;
        signatoryContractId?: number;
    }

    

    






import { TermGroup_SignatoryContractPermissionType } from "../generated-interfaces/Enumerations";
