
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface IAuthenticationDetailsDTO {
        authenticationRequestId: number;
        authenticationMethodType: SignatoryContractAuthenticationMethodType;
        message: string;
        validUntilUTC: Date;
    }

    

    






import { SignatoryContractAuthenticationMethodType } from "../generated-interfaces/Enumerations";
