
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface IAuthenticationResponseDTO {
        signatoryContractAuthenticationRequestId: number;
        username: string;
        password: string;
        code: string;
    }

    

    






