
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface ICopyInvoiceProductModel {
        productId: number;
        purchasePrice: number;
        salesPrice: number;
        productUnit: string;
        priceListTypeId: number;
        priceListHeadId: number;
        sysWholesellerName: string;
        customerId: number;
        origin: PriceListOrigin;
    }

    

    

    export interface IProductsInStockModel {
        productIds: number[];
        stockId: number;
    }

    

    

    export interface ISearchProductPricesModel {
        priceListTypeId: number;
        customerId: number;
        currencyId: number;
        number: string;
        providerType: number;
    }

    

    

    export interface IProductStatisticsModel {
        productId: number;
        originType: number;
        allItemSelection: TermGroup_ChangeStatusGridAllItemsSelection;
    }

    

    

    export interface ISaveInvoiceProductModel {
        invoiceProduct: IInvoiceProductDTO;
        priceLists: IPriceListDTO[];
        categoryRecords: ICompanyCategoryRecordDTO[];
        stocks: IStockDTO[];
        translations: ICompTermDTO[];
        extrafields: IExtraFieldRecordDTO[];
    }

    

    

    export interface IImportStockBalances {
        stockInventoryHeadId: number;
        wholesellerId: number;
        stockId: number;
        createVoucher: boolean;
        fileName: string;
        fileString: string;
        fileData: number[][];
    }

    

    

    export interface IProductsSimpleModel {
        productIds: number[];
    }

    

    

    export interface ISaveInvoiceProjectModel {
        invoiceProject: ITimeProjectDTO;
        priceLists: IDecimalKeyValue[];
        categoryRecords: ICompanyCategoryRecordDTO[];
        accountSettings: IAccountingSettingDTO[];
        projectUsers: IProjectUserDTO[];
        newPricelist: boolean;
        pricelistName: string;
    }

    

    

    export interface ISavePurchaseStatus {
        purchaseId: number;
        status: SoeOriginStatus;
    }

    

    

    export interface ISavePurchaseModel {
        modifiedFields: Record<string, any>;
        originUsers: IOriginUserDTO[];
        newRows: IPurchaseRowDTO[];
        modifiedRows: Record<string, any>[];
    }

    

    

    export interface ISendPurchaseEmail {
        purchaseId: number;
        purchaseIds: number[];
        reportId: number;
        emailTemplateId: number;
        langId?: number;
        recipients: number[];
        singleRecipient: string;
    }

    

    

    export interface IGetFilteredEDIEntrysModel {
        classification: number;
        originType: number;
        billingTypes: number[];
        buyerId: string;
        dueDate?: Date;
        invoiceDate?: Date;
        orderNr: string;
        orderStatuses: number[];
        sellerOrderNr: string;
        ediStatuses: number[];
        sum: number;
        supplierNrName: string;
        allItemsSelection?: TermGroup_ChangeStatusGridAllItemsSelection;
    }

    

    

    export interface ISupplierAgreementModel {
        wholesellerId: number;
        priceListTypeId: number;
        generalDiscount: number;
        files: IFileDTO[];
    }

    

    

    export interface IFilterExpensesModel {
        employeeId: number;
        from: Date;
        to: Date;
        employees: number[];
        projects: number[];
        orders: number[];
        employeeCategories: number[];
    }

    

    

    export interface IProductUnitModel {
        productUnit: IProductUnitDTO;
        translations: ICompTermDTO[];
    }

    

    

    export interface IProductUnitFileModel {
        productIds: number[];
        fileData: number[][];
    }

    

    

    export interface ISearchCustomerInvoiceRowModel {
        projects: number[];
        orders: number[];
        customers: number[];
        orderTypes: number[];
        orderContractTypes: number[];
        from: Date;
        to: Date;
        onlyValid: boolean;
        onlyMine: boolean;
        customerInvoiceRowId?: number;
    }

    

    

    export interface IGetProjectEmployeesModel {
        addEmptyRow: boolean;
        getHidden: boolean;
        addNoReplacementEmployee: boolean;
        includeEmployeeId?: number;
        fromDateString: string;
        toDateString: string;
        employeeCategories: number[];
    }

    

    

    export interface ISaveIntrastatTransactionModel {
        transactions: IIntrastatTransactionDTO[];
        originId: number;
        originType: number;
    }

    

    

    export interface ISavePriceListTypeModel {
        priceListType: IPriceListTypeDTO;
        priceLists: IPriceListDTO[];
    }

    

    

    export interface IPriceListUpdateModel {
        priceUpdate: IPriceUpdateDTO;
        priceListTypeIds: number[];
        updateExisting: boolean;
        dateFrom?: Date;
        dateTo?: Date;
        productNrFrom: string;
        productNrTo: string;
        materialCodeId: number;
        vatType: number;
        productGroupId: number;
        priceComparisonDate: Date;
        quantityFrom: number;
        quantityTo?: number;
    }

    

    

    export interface ISupplierProductPriceUpdateModel {
        priceUpdate: IPriceUpdateDTO;
        supplierProductIds: number[];
        updateExisting: boolean;
        dateFrom?: Date;
        dateTo?: Date;
        priceComparisonDate: Date;
        currencyId: number;
        quantityFrom?: number;
        quantityTo?: number;
    }

    

    

    export interface ISupplierNetPricesDeleteModel {
        wholsellerNetPriceRowIds: number[];
    }

    

    






import { IAccountingSettingDTO } from "../generated-interfaces/AccountingSettingDTO";
import { IIntrastatTransactionDTO } from "../generated-interfaces/CommodityCodeDTO";
import { SoeOriginStatus, PriceListOrigin, TermGroup_ChangeStatusGridAllItemsSelection } from "../generated-interfaces/Enumerations";
import { IExtraFieldRecordDTO } from "../generated-interfaces/ExtraFieldDTO";
import { IDecimalKeyValue } from "../generated-interfaces/GenericType";
import { IInvoiceProductDTO } from "../generated-interfaces/InvoiceProductDTOs";
import { IPriceListDTO } from "../generated-interfaces/PriceListDTOs";
import { IPriceListTypeDTO } from "../generated-interfaces/PriceListTypeDTOs";
import { IPriceUpdateDTO } from "../generated-interfaces/PriceUpdateDTO";
import { IPurchaseRowDTO } from "../generated-interfaces/PurchaseDTOs";
import { ICompanyCategoryRecordDTO, ICompTermDTO, IOriginUserDTO, IProductUnitDTO, ITimeProjectDTO, IProjectUserDTO, IStockDTO, IFileDTO } from "../generated-interfaces/SOECompModelDTOs";
