// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.

export interface ICommodityCodeDTO {
  sysIntrastatCodeId: number;
  intrastatCodeId?: number;
  code: string;
  text: string;
  useOtherQuantity: boolean;
  startDate?: Date;
  endDate?: Date;
  isActive: boolean;
}

export interface IIntrastatTransactionDTO {
  intrastatTransactionId: number;
  originId: number;
  intrastatCodeId: number;
  intrastatTransactionType: number;
  productUnitId?: number;
  sysCountryId?: number;
  netWeight?: number;
  otherQuantity: string;
  notIntrastat: boolean;
  amount?: number;
  state: SoeEntityState;
  customerInvoiceRowId?: number;
  rowNr: number;
  productNr: string;
  productName: string;
  quantity: number;
  productUnitCode: string;
}

export interface IIntrastatTransactionExportDTO {
  actorCountryId?: number;
  currencyId: number;
  originType: number;
  seqNr?: number;
  originNr: string;
  originTypeName: string;
  name: string;
  vatNr: string;
  country: string;
  originCountry: string;
  intrastatCode: string;
  intrastatCodeName: string;
  intrastatTransactionTypeName: string;
  invoiceDate?: Date;
  voucherDate?: Date;
  amountCurrency: number;
  currencyCode: string;
  isPrivatePerson: boolean;
}

import { inherits } from 'util';
import { SoeEntityState } from '../generated-interfaces/Enumerations';
