
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface IContactAddressItem {
        contactId: number;
        contactAddressItemType: ContactAddressItemType;
        isSecret: boolean;
        isAddress: boolean;
        typeName: string;
        icon: string;
        name: string;
        displayAddress: string;
        contactAddressId: number;
        sysContactAddressTypeId: number;
        addressName: string;
        address: string;
        addressIsSecret: boolean;
        addressCO: string;
        addressCOIsSecret: boolean;
        postalCode: string;
        postalAddress: string;
        postalIsSecret: boolean;
        country: string;
        countryIsSecret: boolean;
        streetAddress: string;
        streetAddressIsSecret: boolean;
        entranceCode: string;
        entranceCodeIsSecret: boolean;
        contactEComId: number;
        sysContactEComTypeId: number;
        eComText: string;
        eComDescription: string;
        eComIsSecret: boolean;
    }

    

    






import { ContactAddressItemType } from "../generated-interfaces/Enumerations";
