
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface ICommodityCodeUploadDTO {
        selectedDate: Date;
        year: number;
        fileString: string;
        fileName: string;
    }

    

    

    export interface IUpdateEntityStatesModel {
        dict: Record<number, boolean>;
        skipStateValidation?: boolean;
    }

    

    

    export interface ISaveUserGridStateModel {
        grid: string;
        gridState: string;
    }

    

    

    export interface ISaveCustomerModel {
        customer: ICustomerDTO;
        houseHoldTaxApplicants: IHouseholdTaxDeductionApplicantDTO[];
        extraFields: IExtraFieldRecordDTO[];
    }

    

    

    export interface IUpdateIsPrivatePerson {
        id: number;
        isPrivatePerson: boolean;
    }

    

    

    export interface ICustomerUpdateGrid {
        model: IUpdateEntityStatesModel;
        items: IUpdateIsPrivatePerson[];
    }

    

    

    export interface ISaveAttestWorkFlowForInvoicesModel {
        idsToTransfer: number[];
        sendMessage: boolean;
    }

    

    

    export interface ISaveAttestWorkFlowForMultipleInvoicesModel {
        attestWorkFlowHead: IAttestWorkFlowHeadDTO;
        invoiceIds: number[];
    }

    

    

    export interface ICustomerSearchModel {
        actorCustomerId: number;
        customerNr: string;
        name: string;
        billingAddress: string;
        deliveryAddress: string;
        note: string;
    }

    

    

    export interface IGeneralProductStatisticsModel {
        originType: number;
        fromDate: Date;
        toDate: Date;
    }

    

    

    export interface ITextBlockModel {
        entity: number;
        textBlock: ITextblockDTO;
        translations: ICompTermDTO[];
    }

    

    

    export interface IExtraFieldRecordsModel {
        records: IExtraFieldRecordDTO[];
        recordId: number;
        entity: number;
    }

    

    

    export interface IMoveProjectTimeBlocksToOrderModel {
        customerInvoiceId: number;
        customerInvoiceRowId: number;
        projectTimeBlockIds: number[];
    }

    

    

    export interface IMoveProjectTimeBlocksToDateModel {
        selectedDate: string;
        projectTimeBlockIds: number[];
    }

    

    

    export interface IGetProjectTimeBlocksForTimesheetModel {
        employeeId: number;
        from: Date;
        to: Date;
        employees: number[];
        projects: number[];
        orders: number[];
        groupByDate: boolean;
        incPlannedAbsence: boolean;
        incInternOrderText: boolean;
        employeeCategories: number[];
        timeDeviationCauses: number[];
    }

    

    

    export interface IImportIOModel {
        importHeadType: TermGroup_IOImportHeadType;
        ioIds: number[];
        useAccountDistribution: boolean;
        useAccoungDims: boolean;
        defaultDim1AccountId: number;
        defaultDim2AccountId: number;
        defaultDim3AccountId: number;
        defaultDim4AccountId: number;
        defaultDim5AccountId: number;
        defaultDim6AccountId: number;
    }

    

    

    export interface ISearchCustomerInvoiceModel {
        number: string;
        externalNr: string;
        customerNr: string;
        customerName: string;
        internalText: string;
        projectNr: string;
        projectName: string;
        originType: number;
        customerId?: number;
        projectId?: number;
        userId?: number;
        ignoreInvoiceId?: number;
        ignoreChildren: boolean;
        includePreliminary?: boolean;
        includeVoucher?: boolean;
        fullyPaid?: boolean;
    }

    

    

    export interface IRefreshBatchUpdateOptionsModel {
        entityType: SoeEntityType;
        batchUpdate: IBatchUpdateDTO;
    }

    

    

    export interface IPerformBatchUpdateModel {
        entityType: SoeEntityType;
        batchUpdates: IBatchUpdateDTO[];
        ids: number[];
        filterIds: number[];
    }

    

    

    export interface IParseRowsModel {
    }

    

    






import { IBatchUpdateDTO } from "../generated-interfaces/BatchUpdateDTO";
import { ICustomerDTO } from "../generated-interfaces/CustomerDTO";
import { SoeEntityType, TermGroup_IOImportHeadType } from "../generated-interfaces/Enumerations";
import { IExtraFieldRecordDTO } from "../generated-interfaces/ExtraFieldDTO";
import { IAttestWorkFlowHeadDTO, ICompTermDTO, IHouseholdTaxDeductionApplicantDTO, ITextblockDTO } from "../generated-interfaces/SOECompModelDTOs";
