
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface ICsrResponseDTO {
        personnummer: string;
        skatteform: string;
        skattetabell: string;
        staendejamkningprocent: number;
        felkod: string;
        felmeddelande: string;
        procentbeslut: number;
        giltigtom: string;
        giltigfrom: string;
        year: number;
        errorMessage: string;
        employeeId: number;
    }

    

    






