
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface IDateRangeDTO {
        start: Date;
        stop: Date;
        value: string;
        comment: string;
        days: number;
        minutes: number;
    }

    

    






