
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface ISaveAccountModel {
        account: IAccountEditDTO;
        translations: ICompTermDTO[];
        accountMappings: IAccountMappingDTO[];
        categoryAccounts: ICategoryAccountDTO[];
        extraFields: IExtraFieldRecordDTO[];
        skipStateValidation?: boolean;
    }

    

    

    export interface ISaveAccountSmallModel {
        accountNr: string;
        name: string;
        accountTypeId: number;
        vatAccountId: number;
        sruCode1Id: number;
    }

    

    

    export interface ISaveVoucherModel {
        voucherHead: IVoucherHeadDTO;
        accountingRows: IAccountingRowDTO[];
        householdRowIds: number[];
        revertVatVoucherId?: number;
        files: IFileUploadDTO[];
    }

    

    

    export interface IEditVoucherNrModel {
        voucherHeadId: number;
        newVoucherNr: number;
    }

    

    

    export interface ISaveAccountDistributionModel {
        accountDistributionHead: IAccountDistributionHeadDTO;
        accountDistributionRows: IAccountDistributionRowDTO[];
    }

    

    

    export interface ISaveAccountDimModel {
        accountDim: IAccountDimDTO;
        reset: boolean;
    }

    

    

    export interface ITransferToAccountDistributionEntryModel {
        accountDistributionEntryDTOs: IAccountDistributionEntryDTO[];
        periodDate: Date;
        accountDistributionType: number;
    }

    

    

    export interface ITransferAccountDistributionEntryToVoucherModel {
        accountDistributionEntryDTOs: IAccountDistributionEntryDTO[];
        accountDistributionType: number;
    }

    

    

    export interface IReverseAccountDistributionEntryModel {
        accountDistributionEntryDTOs: IAccountDistributionEntryDTO[];
        accountDistributionType: number;
    }

    

    

    export interface IDeleteDistributionEntryModel {
        accountDistributionEntryDTOs: IAccountDistributionEntryDTO[];
        accountDistributionType: number;
    }

    

    

    export interface ISaveAccountYearBalanceModel {
        accountYearId: number;
        items: IAccountYearBalanceFlatDTO[];
    }

    

    

    export interface ISaveAccountYearModel {
        accountYear: IAccountYearDTO;
        voucherSeries: IVoucherSeriesDTO[];
        keepNumbers: boolean;
    }

    

    

    export interface ISaveSupplierModel {
        supplier: ISupplierDTO;
        files: IFileUploadDTO[];
        extraFields: IExtraFieldRecordDTO[];
    }

    

    

    export interface ITransferEdiStateModel {
        idsToTransfer: number[];
        stateTo: number;
    }

    

    

    export interface ITransferSupplierInvoiceRowsToOrderModel {
        customerInvoiceId: number;
        supplierInvoiceId: number;
        supplierInvoiceProductRowIds: number[];
        wholesellerId: number;
    }

    

    

    export interface IGetResultPerPeriodModel {
        key: string;
        noOfPeriods: number;
        accountYearId: number;
        accountId: number;
        getPrevious: boolean;
        dims: number[];
    }

    

    

    export interface IBlockPaymentModel {
        invoiceId: number;
        block: boolean;
        reason: string;
    }

    

    

    export interface IInvoiceTextActionModel {
        type: InvoiceTextType;
        invoiceId?: number;
        ediEntryId?: number;
        applyAction: boolean;
        reason: string;
    }

    

    

    export interface IGetSupplierCentralCountersAndBalanceModel {
        counterTypes: number[];
        supplierId: number;
    }

    

    

    export interface ISavePaymentImportIODTOModel {
        items: IPaymentImportIODTO[];
        bulkPayDate: Date;
        accountYearId: number;
    }

    

    

    export interface ISaveCustomerPaymentImportIODTOModel {
        items: IPaymentImportIODTO[];
        bulkPayDate: Date;
        accountYearId: number;
        paymentMethodId: number;
    }

    

    

    export interface IPaymentMethodsGetModel {
        originTypeIds: number[];
        addEmptyRow: boolean;
    }

    

    

    export interface ICustomerInvoicesGridModel {
        classification: number;
        allItemsSelection: number;
        originType: number;
        loadOpen: boolean;
        loadClosed: boolean;
        onlyMine: boolean;
        loadActive: boolean;
        billing: boolean;
        modifiedIds: number[];
    }

    

    

    export interface IInvoicesForProjectCentralModel {
        classification: number;
        originType: number;
        projectId: number;
        loadChildProjects: boolean;
        fromDate?: Date;
        toDate?: Date;
        invoiceIds: number[];
    }

    

    

    export interface IProjectSearchModel {
        number: string;
        name: string;
        customerNr: string;
        customerName: string;
        managerName: string;
        orderNr: string;
        onlyActive: boolean;
        hidden: boolean;
        showWithoutCustomer: boolean;
        loadMine: boolean;
        customerId?: number;
        showAllProjects: boolean;
    }

    

    

    export interface ICalculateAccountBalanceForAccountsFromVoucherModel {
        accountYearId: number;
    }

    

    

    export interface ISaveInventoryWriteOffTemplateModel {
        inventoryWriteOffTemplate: IInventoryWriteOffTemplateDTO;
        accountSettings: IAccountingSettingDTO[];
    }

    

    

    export interface IGetLiquidityPlanningModel {
        from: Date;
        to: Date;
        exclusion?: Date;
        balance: number;
        unpaid: boolean;
        paidUnchecked: boolean;
        paidChecked: boolean;
    }

    

    

    export interface IGetCSRResponseModel {
        idsToTransfer: number[];
        year: number;
    }

    

    

    export interface ISaveAdjustmentModel {
        inventoryId: number;
        type: TermGroup_InventoryLogType;
        voucherSeriesTypeId: number;
        amount: number;
        date: Date;
        note: string;
        accountRowItems: IAccountingRowDTO[];
    }

    

    

    export interface ISaveInventoryNotesModel {
        inventoryId: number;
        description: string;
        notes: string;
    }

    

    

    export interface ICompanyGroupTransferModel {
        transferType: CompanyGroupTransferType;
        accountYearId: number;
        voucherSeriesId: number;
        periodFrom: number;
        periodTo: number;
        includeIB: boolean;
        budgetCompanyFrom?: number;
        budgetCompanyGroup?: number;
        budgetChild?: number;
    }

    

    

    export interface IFInvoiceModel {
        fileName: string;
        fileString: string;
        extention: string;
        entity: SoeEntityType;
    }

    

    






import { IAccountingRowDTO } from "../generated-interfaces/AccountingRowDTO";
import { IAccountingSettingDTO } from "../generated-interfaces/AccountingSettingDTO";
import { CompanyGroupTransferType, SoeEntityType, InvoiceTextType, TermGroup_InventoryLogType } from "../generated-interfaces/Enumerations";
import { IExtraFieldRecordDTO } from "../generated-interfaces/ExtraFieldDTO";
import { IAccountEditDTO, IAccountDimDTO, IAccountDistributionEntryDTO, IAccountDistributionHeadDTO, IAccountDistributionRowDTO, IAccountMappingDTO, IAccountYearDTO, IAccountYearBalanceFlatDTO, ICategoryAccountDTO, ICompTermDTO, IInventoryWriteOffTemplateDTO, IFileUploadDTO, ISupplierDTO, IPaymentImportIODTO } from "../generated-interfaces/SOECompModelDTOs";
import { IVoucherHeadDTO } from "../generated-interfaces/VoucherHeadDTOs";
import { IVoucherSeriesDTO } from "../generated-interfaces/VoucherSeriesDTOs";
