
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface IEmploymentTypeDTO {
        employmentTypeId?: number;
        type: number;
        name: string;
        description: string;
        code: string;
        standard: boolean;
        excludeFromWorkTimeWeekCalculationOnSecondaryEmployment: boolean;
        settingOnly: boolean;
        externalCode: string;
        state: SoeEntityState;
        active: boolean;
        typeName: string;
        codeAndName: string;
        disableActive: boolean;
        hideEdit: boolean;
        isActive?: boolean;
    }

    

    

    export interface IEmploymentTypeGridDTO {
        employmentTypeId?: number;
        gridId: number;
        type: number;
        typeName: string;
        name: string;
        description: string;
        code: string;
        allowEdit: boolean;
        excludeFromWorkTimeWeekCalculationOnSecondaryEmployment: boolean;
        settingOnly: boolean;
        externalCode: string;
        state: SoeEntityState;
        standard: boolean;
        standardText: string;
    }

    

    

    export interface IEmploymentTypeSmallDTO {
        id?: number;
        name: string;
        type: number;
        active: boolean;
    }

    

    






import { SoeEntityState } from "../generated-interfaces/Enumerations";
