
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface IEmployeeCollectiveAgreementDTO {
        employeeCollectiveAgreementId: number;
        actorCompanyId: number;
        code: string;
        externalCode: string;
        name: string;
        description: string;
        employeeGroupId: number;
        payrollGroupId?: number;
        vacationGroupId?: number;
        annualLeaveGroupId?: number;
        created?: Date;
        createdBy: string;
        modified?: Date;
        modifiedBy: string;
        state: SoeEntityState;
        employeeGroupName: string;
        payrollGroupName: string;
        vacationGroupName: string;
        annualLeaveGroupName: string;
    }

    

    

    export interface IEmployeeCollectiveAgreementGridDTO {
        employeeCollectiveAgreementId: number;
        employeeGroupName: string;
        payrollGroupName: string;
        vacationGroupName: string;
        annualLeaveGroupName: string;
        code: string;
        externalCode: string;
        name: string;
        description: string;
        employeeTemplateNames: string;
        state: SoeEntityState;
    }

    

    






import { SoeEntityState } from "../generated-interfaces/Enumerations";
