
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface IExportDTO {
        exportId: number;
        actorCompanyId: number;
        exportDefinitionId: number;
        module: number;
        standard: boolean;
        name: string;
        filename: string;
        emailaddress: string;
        subject: string;
        attachFile: boolean;
        sendDirect: boolean;
        created?: Date;
        createdBy: string;
        modified?: Date;
        modifiedBy: string;
        state: number;
        guid: string;
        specialFunctionality: string;
    }

    

    

    export interface IExportGridDTO {
        exportId: number;
        name: string;
    }

    

    

    export interface IExportDefinitionDTO {
        exportDefinitionId: number;
        actorCompanyId: number;
        sysExportHeadId?: number;
        name: string;
        type?: number;
        separator: string;
        xmlTagHead: string;
        specialFunctionality: string;
        created?: Date;
        createdBy: string;
        modified?: Date;
        modifiedBy: string;
        state: SoeEntityState;
        exportDefinitionLevels: IExportDefinitionLevelDTO[];
        exportHeadName: string;
        isStandardExport: string;
        exportTypeName: string;
        reportSelectionId?: number;
        reportUserSelection: IReportUserSelectionDTO;
    }

    

    

    export interface IExportDefinitionGridDTO {
        exportDefinitionId: number;
        actorCompanyId: number;
        name: string;
        type?: number;
        created?: Date;
        createdBy: string;
        modified?: Date;
        modifiedBy: string;
        state: SoeEntityState;
    }

    

    

    export interface IExportDefinitionLevelDTO {
        exportDefinitionLevelId: number;
        exportDefinitionId: number;
        level: number;
        xml: string;
        useColumnHeaders: boolean;
        exportDefinitionLevelColumns: IExportDefinitionLevelColumnDTO[];
    }

    

    

    export interface IExportDefinitionLevelColumnDTO {
        exportDefinitionLevelColumnId: number;
        exportDefinitionLevelId: number;
        name: string;
        description: string;
        key: string;
        position: number;
        defaultValue: string;
        matrixDefinitionColumn: IMatrixDefinitionColumn;
        isDelimiter: boolean;
        isPosition: boolean;
        fillChar: string;
        fillBeginning?: boolean;
        formatDate: string;
        columnLength: number;
        xmlTag: string;
        created?: Date;
        createdBy: string;
        modified?: Date;
        modifiedBy: string;
        state: SoeEntityState;
        columnHeader: string;
        convertValue: string;
        getDateValueFromKey: string;
    }

    

    






import { SoeEntityState } from "../generated-interfaces/Enumerations";
import { IMatrixDefinitionColumn } from "../generated-interfaces/MatrixResult";
import { IReportUserSelectionDTO } from "../generated-interfaces/SOECompModelDTOs";
