// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.

export interface IFieldSettingGridDTO {
  formName: string;
  fieldId: number;
  fieldName: string;
  companySettingsSummary: string;
  roleSettingsSummary: string;
}

export interface IFieldSettingDTO {
  formId: number;
  formName: string;
  fieldId: number;
  fieldName: string;
  type: SoeFieldSettingType;
  companySettingsSummary: string;
  roleSettingsSummary: string;
  companySetting: ICompanyFieldSettingDTO;
  roleSettings: IRoleFieldSettingDTO[];
}

export interface ICompanyFieldSettingDTO {
  actorCompanyId: number;
  label: string;
  visible?: boolean;
  skipTabStop?: boolean;
  readOnly?: boolean;
  boldLabel?: boolean;
}

export interface IRoleFieldSettingDTO {
  roleId: number;
  roleName: string;
  label: string;
  visible?: boolean;
  skipTabStop?: boolean;
  readOnly?: boolean;
  boldLabel?: boolean;
  visibleName: string;
}

import { SoeFieldSettingType } from '../generated-interfaces/Enumerations';
