
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface IFilesLookupDTO {
        entity: SoeEntityType;
        files: IImportFileDTO[];
    }

    

    






import { SoeEntityType } from "../generated-interfaces/Enumerations";
import { IImportFileDTO } from "../generated-interfaces/ImportFileDTO";
