
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface IFinnishTaxExportDTO {
        lengthOfTaxPeriod: number;
        taxPeriod: number;
        taxPeriodYear: number;
        noActivity: boolean;
        correction: boolean;
        cause: number;
    }

    

    

    export interface IFinnishTaxExporFiletDTO {
        name: string;
        extension: string;
        data: string;
    }

    

    






