
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface IHouseholdTaxDeductionFileRowDTO {
        customerInvoiceRowId: number;
        invoiceNr: string;
        name: string;
        socialSecNr: string;
        property: string;
        apartmentNr: string;
        cooperativeOrgNr: string;
        invoiceTotalAmount: number;
        workAmount: number;
        paidAmount: number;
        appliedAmount: number;
        nonValidAmount: number;
        comment: string;
        paidDate?: Date;
        houseHoldTaxDeductionType: TermGroup_HouseHoldTaxDeductionType;
        types: IHouseholdTaxDeductionFileRowTypeDTO[];
    }

    

    

    export interface IHouseholdTaxDeductionFileRowTypeDTO {
        sysHouseholdTypeId: number;
        text: string;
        xmlTag: string;
        hours: number;
        amount: number;
    }

    

    






import { TermGroup_HouseHoldTaxDeductionType } from "../generated-interfaces/Enumerations";
