
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface IImportFileDTO {
        dataStorageId: number;
        fileName: string;
    }

    

    






