
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface IImportSelectionGridRowDTO {
      fileName: string;
      fileType: string;
      dataStorageId: number;
      import: IImportDTO;
      importId?: number;
      importName: string;
      message: string;
      disableImport: boolean;
      doImport: boolean;
    }

    

    






import { IImportDTO } from "../generated-interfaces/SOECompModelDTOs";
