
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface IInvoiceMatchingDTO {
        isSelected: boolean;
        isCredit: boolean;
        isEditable: boolean;
        hasMatches: boolean;
        invoiceId: number;
        paymentRowId: number;
        voucherHeadId: number;
        invoiceMatchingId: number;
        actorId: number;
        matchCodeId: number;
        invoiceNr: string;
        orderNr: string;
        paymentNr: string;
        invoiceTotalAmount: number;
        invoiceVatAmount: number;
        invoicePayedAmount: number;
        invoiceVatRate: number;
        invoiceVatAccountId: number;
        type: number;
        billingType: TermGroup_BillingType;
        typeName: string;
        typeNameId?: number;
        amount: number;
        actorName: string;
        invoiceMatchAmount: number;
        originStatus: number;
        createdDate: Date;
        count: number;
        date?: Date;
        registrationType: OrderInvoiceRegistrationType;
    }

    

    






import { OrderInvoiceRegistrationType, TermGroup_BillingType } from "../generated-interfaces/Enumerations";
