
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface IInvoiceTextDTO {
        invoiceId?: number;
        ediEntryId?: number;
        text: string;
        type: InvoiceTextType;
        created?: Date;
        createdBy: string;
        modified?: Date;
        modifiedBy: string;
        state: SoeEntityState;
    }

    

    






import { SoeEntityState, InvoiceTextType } from "../generated-interfaces/Enumerations";
