
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface ILiquidityPlanningDTO {
        invoiceId: number;
        invoiceNr: string;
        originType: SoeOriginType;
        liquidityPlanningTransactionId?: number;
        date: Date;
        transactionType: LiquidityPlanningTransactionType;
        transactionTypeName: string;
        specification: string;
        valueIn: number;
        valueOut: number;
        total: number;
        created?: Date;
        createdBy: string;
        modified?: Date;
        modifiedBy: string;
    }

    

    






import { SoeOriginType, LiquidityPlanningTransactionType } from "../generated-interfaces/Enumerations";
