
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface ISoeBankerAuthorizationRequestModel {
        onboardingRequestIds: number[];
    }

    

    






