
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface ISoeProgressInfo {
        actorCompanyId: number;
        id: number;
        soeProgressInfoType: SoeProgressInfoType;
        pollingKey: string;
        abort: boolean;
        done: boolean;
        error: boolean;
        errorMessage: string;
        created: Date;
        age: string;
        timeSinceLastAction: string;
        baseMessage: string;
        message: string;
    }

    

    






import { SoeProgressInfoType } from "../generated-interfaces/Enumerations";
