
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface IMultiCompanyErrorDTO {
        targetActorCompanyId: number;
        targetCompanyName: string;
        errorMessage: string;
        errorCode: number;
    }

    

    






