
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface IPaymentImportRowsDto {
        paymentMethodId: number;
        contents: number[][];
        base64String: string;
        fileName: string;
        batchId: number;
        paymentImportId: number;
        importType: ImportPaymentType;
    }

    

    






import { ImportPaymentType } from "../generated-interfaces/Enumerations";
