
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface IPriceListTypeMarkupDTO {
        priceListTypeId: number;
        markup: number;
    }

    

    






