
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface IProductStatisticsRequest {
        productIds: number[];
        fromDate: Date;
        toDate: Date;
        originType: SoeOriginType;
        includeServiceProducts: boolean;
    }

    

    






import { SoeOriginType } from "../generated-interfaces/Enumerations";
