
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface IProductStatisticsDTO {
        originType: SoeOriginType;
        originTypeName: string;
        productId: number;
        productNr: string;
        productName: string;
        year: string;
        month: string;
        invoiceDate?: Date;
        purchaseDeliveryDate?: Date;
        invoiceId: number;
        invoiceNr: string;
        orderId: number;
        orderNr: string;
        purchaseId: number;
        purchaseNr: string;
        customerNr: string;
        customerName: string;
        supplierNr: string;
        supplierName: string;
        purchaseQty: number;
        customerInvoiceQty: number;
        customerInvoiceAmount: number;
        marginalIncome: number;
        marginalRatio: number;
        vatType: TermGroup_InvoiceProductVatType;
    }

    

    






import { SoeOriginType, TermGroup_InvoiceProductVatType } from "../generated-interfaces/Enumerations";
