
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface IPurchaseCartDTO {
        purchaseCartId: number;
        seqNr: number;
        name: string;
        description: string;
        priceStrategy: number;
        created?: Date;
        createdBy: string;
        modified?: Date;
        modifiedBy: string;
        status: number;
        selectedWholesellerIds: number[];
        state: SoeEntityState;
        purchaseCartRows: IPurchaseCartRowDTO[];
    }

    

    

    export interface IChangeCartStateModel {
        ids: number[];
        stateTo: TermGroup_PurchaseCartStatus;
    }

    

    

    export interface IPurchaseCartRowDTO {
        purchaseCartRowId: number;
        purchaseCartId: number;
        sysProductId: number;
        productNr: string;
        productName: string;
        productInfo: string;
        imageUrl: string;
        externalId?: number;
        type: number;
        purchasePrice?: number;
        sysPricelistHeadId: number;
        wholesellerNetPriceId: number;
        quantity: number;
        sysWholesellerId: number;
        state: SoeEntityState;
        created?: Date;
        createdBy: string;
        modified?: Date;
        modifiedBy: string;
    }

    

    

    export interface ITransferInvoiceDTO {
        invoiceId: number;
        purchaseCartId: number;
    }

    

    






import { SoeEntityState, TermGroup_PurchaseCartStatus } from "../generated-interfaces/Enumerations";
