
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface IReportPrintDTO {
        reportId: number;
        ids: number[];
        queue: boolean;
        returnAsBinary: boolean;
        exportType: TermGroup_ReportExportType;
    }

    

    

    export interface IProjectPrintDTO {
        sysReportTemplateTypeId: SoeReportTemplateType;
        includeChildProjects: boolean;
        dateFrom?: Date;
        dateTo?: Date;
    }

    

    

    export interface IBalanceListPrintDTO {
        companySettingType: CompanySettingType;
        paymentRowIds: number[];
    }

    

    

    export interface IHouseholdTaxDeductionPrintDTO {
        sysReportTemplateTypeId: SoeReportTemplateType;
        sequenceNumber: number;
        useGreen: boolean;
    }

    

    

    export interface ICustomerInvoicePrintDTO {
        sysReportTemplateTypeId: SoeReportTemplateType;
        attachmentIds: number[];
        checklistIds: number[];
        printTimeReport: boolean;
        includeOnlyInvoiced: boolean;
        orderInvoiceRegistrationType: OrderInvoiceRegistrationType;
        invoiceCopy: boolean;
        asReminder: boolean;
        mergePdfs: boolean;
        reportLanguageId?: number;
    }

    

    






import { OrderInvoiceRegistrationType, SoeReportTemplateType, TermGroup_ReportExportType, CompanySettingType } from "../generated-interfaces/Enumerations";
