
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface IGetReportsForTypesModel {
        reportTemplateTypeIds: number[];
        onlyOriginal: boolean;
        onlyStandard: boolean;
        module?: SoeModule;
    }

    

    

    export interface IGetPurchasePrintUrlModel {
        purchaseIds: number[];
        emailRecipients: number[];
        reportId: number;
        languageId: number;
    }

    

    

    export interface IGenericPrintUrlModel {
        itemIds: number[];
        reportId: number;
        sysReportTemplateTypeId: number;
        secondaryItemIds: number[];
    }

    

    






import { SoeModule } from "../generated-interfaces/Enumerations";
