
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface ISearchVoucherRowDTO {
        actorCompanyId: number;
        voucherHeadId: number;
        voucherRowId: number;
        voucherNr: number;
        voucherText: string;
        voucherSeriesName: string;
        debit: number;
        credit: number;
        created?: Date;
        createdBy: string;
        dim1AccountId: number;
        dim1AccountNr: string;
        dim1AccountName: string;
        dim2AccountId: number;
        dim2AccountNr: string;
        dim2AccountName: string;
        dim3AccountId: number;
        dim3AccountNr: string;
        dim3AccountName: string;
        dim4AccountId: number;
        dim4AccountNr: string;
        dim4AccountName: string;
        dim5AccountId: number;
        dim5AccountNr: string;
        dim5AccountName: string;
        dim6AccountId: number;
        dim6AccountNr: string;
        dim6AccountName: string;
        voucherDate: Date;
        invoiceId?: number;
        invoiceNr: string;
        invoiceOriginType?: SoeOriginType;
        invoiceRegistrationType?: OrderInvoiceRegistrationType;
    }

    

    

    export interface ISearchVoucherRowsAngDTO {
        actorCompanyId: number;
        voucherDateFrom?: Date;
        voucherDateTo?: Date;
        voucherSeriesIdFrom: number;
        voucherSeriesIdTo: number;
        debitFrom: number;
        debitTo: number;
        creditFrom: number;
        creditTo: number;
        amountFrom: number;
        amountTo: number;
        voucherText: string;
        createdFrom?: Date;
        createdTo?: Date;
        createdBy: string;
        dim1AccountId: number;
        dim1AccountFr: string;
        dim1AccountTo: string;
        dim2AccountId: number;
        dim2AccountFr: string;
        dim2AccountTo: string;
        dim3AccountId: number;
        dim3AccountFr: string;
        dim3AccountTo: string;
        dim4AccountId: number;
        dim4AccountFr: string;
        dim4AccountTo: string;
        dim5AccountId: number;
        dim5AccountFr: string;
        dim5AccountTo: string;
        dim6AccountId: number;
        dim6AccountFr: string;
        dim6AccountTo: string;
        voucherSeriesTypeIds: number[];
    }

    

    






import { SoeOriginType, OrderInvoiceRegistrationType } from "../generated-interfaces/Enumerations";
