
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface ISearchInvoicesPaymentsAndMatchesDTO {
        actorId: number;
        type: number;
        amountFrom: number;
        amountTo: number;
        dateFrom?: Date;
        dateTo?: Date;
        originType: SoeOriginType;
    }

    

    






import { SoeOriginType } from "../generated-interfaces/Enumerations";
