
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface ISignatoryContractGridDTO {
        signatoryContractId: number;
        actorCompanyId: number;
        parentSignatoryContractId?: number;
        signedByUserId: number;
        creationMethodType: number;
        requiredAuthenticationMethodType: number;
        canPropagate: boolean;
        created: Date;
        revokedAtUTC?: Date;
        revokedAt?: Date;
        revokedBy: string;
        revokedReason: string;
        permissionTypes: number[];
        permissionNames: string[];
        permissions: string;
        authenticationMethod: string;
        recipientUserId: number;
        recipientUserName: string;
    }

    

    






