
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface ISignatoryContractRevokeDTO {
        signatoryContractId: number;
        revokedReason: string;
    }

    

    






