
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.






export enum ServiceType { 
    Unknown = 0,
    Wcf = 1,
    Webforms = 2,
    WebApi = 3,
    WebApiInternal = 4,
    WebserviceExternal = 5,
    TimeSpotOld = 6,
    TimeSpotNew = 7,
    Communicator = 8,
    SoftOneId = 9,
    Logger = 10,
    EdiCore = 11,
    CrGen = 12,
    Ftp = 13,
    SysService = 14,
    TimeStampService = 15,
    WebApiExternal = 16,
    WebTimeStamp = 17,
    Storage = 18,
    SoftOneIdFront = 19,
    SoftOneIdApi = 20,
    SSH = 21,
    Server = 22,
    ScheduleJobs = 23,
    ReportFromWeb = 24,
    SoftOneStatus = 25,
    Selenium = 26
}



