
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface ISupplierAgreementDTO {
        rebateListId: number;
        sysWholesellerId: number;
        wholesellerName: string;
        priceListTypeId?: number;
        priceListTypeName: string;
        discountPercent: number;
        code: string;
        codeType: number;
        date?: Date;
        categoryId?: number;
        state: number;
    }

    

    






