
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface ISupplierInvoiceCostAllocationDTO {
        customerInvoiceRowId: number;
        timeCodeTransactionId: number;
        supplierInvoiceId: number;
        projectId: number;
        orderId: number;
        attestStateId: number;
        timeInvoiceTransactionId?: number;
        createdDate: Date;
        projectAmount: number;
        projectAmountCurrency: number;
        rowAmount: number;
        rowAmountCurrency: number;
        orderAmount: number;
        orderAmountCurrency: number;
        supplementCharge?: number;
        chargeCostToProject: boolean;
        includeSupplierInvoiceImage: boolean;
        isReadOnly: boolean;
        productId?: number;
        productNr: string;
        productName: string;
        timeCodeId: number;
        timeCodeCode: string;
        timeCodeName: string;
        timeCodeDescription: string;
        employeeId?: number;
        employeeNr: string;
        employeeName: string;
        employeeDescription: string;
        projectNr: string;
        projectName: string;
        orderNr: string;
        customerInvoiceNumberName: string;
        attestStateName: string;
        attestStateColor: string;
        state: SoeEntityState;
        isTransferToOrderRow: boolean;
        isConnectToProjectRow: boolean;
    }

    

    






import { SoeEntityState } from "../generated-interfaces/Enumerations";
