
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface ISupplierInvoiceProjectRowDTO {
        state: SoeEntityState;
        timeCodeTransactionId: number;
        amount: number;
        amountCurrency: number;
        amountLedgerCurrency: number;
        amountEntCurrency: number;
        timeInvoiceTransactionId: number;
        supplierInvoiceId: number;
        projectId: number;
        projectNr: string;
        projectName: string;
        projectDescription: string;
        orderIds: number[];
        orderNr: string;
        timeCodeId: number;
        timeCodeCode: string;
        timeCodeName: string;
        timeCodeDescription: string;
        employeeId?: number;
        employeeNr: string;
        employeeName: string;
        employeeDescription: string;
        timeBlockDateId?: number;
        date?: Date;
        chargeCostToProject: boolean;
        includeSupplierInvoiceImage: boolean;
        customerInvoiceId: number;
        customerInvoiceNr: string;
        customerInvoiceCustomerName: string;
        customerInvoiceNumberName: string;
        customerInvoiceDescription: string;
    }

    

    






import { SoeEntityState } from "../generated-interfaces/Enumerations";
