
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.






export enum TimeScheduleBlockType { 
    Schedule = 0,
    Order = 1,
    Booking = 2,
    Standby = 3,
    OnDuty = 4
}



