
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface IShiftAccountingRowDTO {
        timeScheduleTemplateBlockId: number;
        identityName: string;
        dim2Id?: number;
        dim2Nr: string;
        dim2Name: string;
        dim3Id?: number;
        dim3Nr: string;
        dim3Name: string;
        dim4Id?: number;
        dim4Nr: string;
        dim4Name: string;
        dim5Id?: number;
        dim5Nr: string;
        dim5Name: string;
        dim6Id?: number;
        dim6Nr: string;
        dim6Name: string;
    }

    

    

    export interface IShiftRequestStatusDTO {
        messageId: number;
        senderName: string;
        text: string;
        sentDate: Date;
        recipients: IShiftRequestStatusRecipientDTO[];
    }

    

    

    export interface IShiftRequestStatusRecipientDTO {
        userId: number;
        employeeId: number;
        employeeNr: string;
        employeeName: string;
        readDate?: Date;
        answerDate?: Date;
        answerType: XEMailAnswerType;
        modified?: Date;
        modifiedBy: string;
        state: SoeEntityState;
    }

    

    

    export interface IEmployeeListDTO {
        employeeId: number;
        employeeNr: string;
        employeeNrSort: string;
        firstName: string;
        lastName: string;
        sex: TermGroup_Sex;
        annualWorkTimeMinutes: number;
        annualScheduledTimeMinutes: number;
        childRuleWorkedTimeMinutes: number;
        childPeriodBalanceTimeMinutes: number;
        parentWorkedTimeMinutes: number;
        parentScheduledTimeMinutes: number;
        parentRuleWorkedTimeMinutes: number;
        parentPeriodBalanceTimeMinutes: number;
        active: boolean;
        hidden: boolean;
        vacant: boolean;
        isSelected: boolean;
        isGroupHeader: boolean;
        groupName: string;
        employments: IEmployeeListEmploymentDTO[];
        accounts: IEmployeeAccountDTO[];
        categoryRecords: ICompanyCategoryRecordDTO[];
        employeeSkills: IEmployeeSkillDTO[];
        templateSchedules: ITimeScheduleTemplateHeadSmallDTO[];
        employeeSchedules: IDateRangeDTO[];
        absenceRequest: IDateRangeDTO[];
        absenceApproved: IDateRangeDTO[];
        hasAbsenceRequest: boolean;
        hasAbsenceApproved: boolean;
        currentDate?: Date;
        available: IEmployeeListAvailabilityDTO[];
        unavailable: IEmployeeListAvailabilityDTO[];
        employeePostId: number;
        description: string;
        employeePostStatus: SoeEmployeePostStatus;
        name: string;
        hibernatingText: string;
    }

    

    

    export interface IEmployeeListEmploymentDTO {
        dateFrom?: Date;
        dateTo?: Date;
        isSecondaryEmployment: boolean;
        workTimeWeekMinutes: number;
        percent: number;
        minScheduleTime: number;
        maxScheduleTime: number;
        employeeGroupId?: number;
        employeeGroupName: string;
        breakDayMinutesAfterMidnight: number;
        allowShiftsWithoutAccount: boolean;
        isTemporaryPrimary: boolean;
        extraShiftAsDefault: boolean;
        annualLeaveGroupId?: number;
    }

    

    

    export interface IEmployeeListAvailabilityDTO {
        start: Date;
        stop: Date;
        comment: string;
        minutes: number;
    }

    

    

    export interface IShiftDTO {
        type: TermGroup_TimeScheduleTemplateBlockType;
        timeScheduleTemplateBlockId: number;
        timeScheduleEmployeePeriodId: number;
        timeCodeId: number;
        description: string;
        startTime: Date;
        stopTime: Date;
        absenceStartTime: Date;
        absenceStopTime: Date;
        belongsToPreviousDay: boolean;
        belongsToNextDay: boolean;
        timeScheduleTypeId: number;
        timeScheduleTypeCode: string;
        timeScheduleTypeName: string;
        timeScheduleTypeIsNotScheduleTime: boolean;
        timeScheduleTypeFactors: ITimeScheduleTypeFactorSmallDTO[];
        shiftTypeTimeScheduleTypeId: number;
        shiftTypeTimeScheduleTypeCode: string;
        shiftTypeTimeScheduleTypeName: string;
        employeeId: number;
        employeeName: string;
        grossTime: number;
        totalCost: number;
        totalCostIncEmpTaxAndSuppCharge: number;
        breaks: IShiftBreakDTO[];
        timeDeviationCauseId?: number;
        timeDeviationCauseName: string;
        shiftTypeId: number;
        shiftTypeCode: string;
        shiftTypeName: string;
        shiftTypeDesc: string;
        shiftTypeColor: string;
        shiftStatus: TermGroup_TimeScheduleTemplateBlockShiftStatus;
        shiftUserStatus: TermGroup_TimeScheduleTemplateBlockShiftUserStatus;
        isPreliminary: boolean;
        extraShift: boolean;
        substituteShift: boolean;
        isDeleted: boolean;
        accountId?: number;
        accountName: string;
        nbrOfWantedInQueue: number;
        timeScheduleTemplateHeadId?: number;
        nbrOfWeeks: number;
        dayNumber: number;
        originalBlockId: number;
        link?: string;
        isAbsenceRequest: boolean;
        timeLeisureCodeId?: number;
    }

    

    

    export interface IShiftBreakDTO {
        breakId: number;
        timeCodeId: number;
        startTime?: Date;
        belongsToPreviousDay: boolean;
        belongsToNextDay: boolean;
        minutes: number;
        link?: string;
        isPreliminary: boolean;
    }

    

    






import { IDateRangeDTO } from "../generated-interfaces/DateRangeDTO";
import { IEmployeeAccountDTO } from "../generated-interfaces/EmployeeUserDTO";
import { SoeEntityState, SoeEmployeePostStatus, TermGroup_TimeScheduleTemplateBlockShiftStatus, TermGroup_TimeScheduleTemplateBlockShiftUserStatus, TermGroup_Sex, TermGroup_TimeScheduleTemplateBlockType, XEMailAnswerType } from "../generated-interfaces/Enumerations";
import { ICompanyCategoryRecordDTO, IEmployeeSkillDTO, ITimeScheduleTemplateHeadSmallDTO, ITimeScheduleTypeFactorSmallDTO } from "../generated-interfaces/SOECompModelDTOs";
