
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface IUserAgentClientInfoDTO {
        data: string;
        osFamily: string;
        osVersion: string;
        deviceBrand: string;
        deviceFamily: string;
        deviceModel: string;
        userAgentFamily: string;
        userAgentVersion: string;
    }

    

    






