
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface IVoucherRowHistoryViewDTO {
        eventType: string;
        fieldModified: string;
        eventText: string;
        text: string;
        date: string;
        dateTime: Date;
        time: string;
        userName: string;
    }

    

    






