
// This file was generated by TypeWriter. See TypeWriter.Common.tst for reference.



    export interface IVoucherRowDTO {
        voucherRowId: number;
        voucherHeadId: number;
        parentRowId?: number;
        accountDistributionHeadId?: number;
        date?: Date;
        text: string;
        quantity?: number;
        amount: number;
        amountEntCurrency: number;
        merged: boolean;
        state: SoeEntityState;
        voucherNr: number;
        voucherSeriesTypeNr: number;
        voucherSeriesTypeName: string;
        tempRowId: number;
        dim1Id: number;
        dim1Nr: string;
        dim1Name: string;
        dim1UnitStop: boolean;
        dim1AmountStop: number;
        dim2Id: number;
        dim2Nr: string;
        dim2Name: string;
        dim3Id: number;
        dim3Nr: string;
        dim3Name: string;
        dim4Id: number;
        dim4Nr: string;
        dim4Name: string;
        dim5Id: number;
        dim5Nr: string;
        dim5Name: string;
        dim6Id: number;
        dim6Nr: string;
        dim6Name: string;
        startDate?: Date;
        numberOfPeriods?: number;
        rowNr?: number;
        sysVatAccountId?: number;
        dim1AccountType: number;
        accountInternalDTO_forReports: IAccountInternalDTO[];
    }

    

    

    export interface IVoucherRowIODTO {
        voucherRowIOId: number;
        voucherHeadIOId: number;
        actorCompanyId: number;
        import: boolean;
        type: TermGroup_IOType;
        status: TermGroup_IOStatus;
        source: TermGroup_IOSource;
        importHeadType: TermGroup_IOImportHeadType;
        batchId: string;
        errorMessage: string;
        created?: Date;
        createdBy: string;
        modified?: Date;
        modifiedBy: string;
        voucherRowId: number;
        text: string;
        accountNr: string;
        accountDim2Nr: string;
        accountDim3Nr: string;
        accountDim4Nr: string;
        accountDim5Nr: string;
        accountDim6Nr: string;
        accountSieDim1: string;
        accountSieDim3: string;
        accountSieDim6: string;
        amount?: number;
        debetAmount?: number;
        creditAmount?: number;
        quantity?: number;
        statusName: string;
        accountId: number;
        accountName: string;
        accountDim2Id: number;
        accountDim2Name: string;
        accountDim3Id: number;
        accountDim3Name: string;
        accountDim4Id: number;
        accountDim4Name: string;
        accountDim5Id: number;
        accountDim5Name: string;
        accountDim6Id: number;
        accountDim6Name: string;
    }

    

    






import { SoeEntityState, TermGroup_IOStatus, TermGroup_IOType, TermGroup_IOSource, TermGroup_IOImportHeadType } from "../generated-interfaces/Enumerations";
import { IAccountInternalDTO } from "../generated-interfaces/SOECompModelDTOs";
