//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftOne.Soe.Web.soe.economy.preferences.currency.edit {
    
    
    public partial class _default {
        
        /// <summary>
        /// Form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.Form Form1;
        
        /// <summary>
        /// Code control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.SelectEntry Code;
        
        /// <summary>
        /// IntervalType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.SelectEntry IntervalType;
        
        /// <summary>
        /// RateToBase control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.NumericEntry RateToBase;
        
        /// <summary>
        /// RateFromBase control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.NumericEntry RateFromBase;
        
        /// <summary>
        /// RateDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.DateEntry RateDate;
    }
}
