//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftOne.Soe.Web.UserControls {
    
    
    public partial class TimeCodeBase {
        
        /// <summary>
        /// TimeCodeHeading control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal TimeCodeHeading;
        
        /// <summary>
        /// Code control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.TextEntry Code;
        
        /// <summary>
        /// Name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.TextEntry Name;
        
        /// <summary>
        /// Description control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.TextEntry Description;
        
        /// <summary>
        /// Payed control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.CheckBoxEntry Payed;
        
        /// <summary>
        /// Template control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.CheckBoxEntry Template;
        
        /// <summary>
        /// DivTimeCodeSettings control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DivTimeCodeSettings;
        
        /// <summary>
        /// RoundingType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.SelectEntry RoundingType;
        
        /// <summary>
        /// RoundingValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.NumericEntry RoundingValue;
        
        /// <summary>
        /// RegistrationType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.SelectEntry RegistrationType;
        
        /// <summary>
        /// MinutesByConstantRules control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.NumericEntry MinutesByConstantRules;
        
        /// <summary>
        /// DivTimeCodeWork control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DivTimeCodeWork;
        
        /// <summary>
        /// IsWorkOutsideSchedule control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.CheckBoxEntry IsWorkOutsideSchedule;
        
        /// <summary>
        /// DivTimeCodeAbsence control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DivTimeCodeAbsence;
        
        /// <summary>
        /// IsAbsence control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.CheckBoxEntry IsAbsence;
        
        /// <summary>
        /// DivInvoiceProducts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DivInvoiceProducts;
        
        /// <summary>
        /// InvoiceProducts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.FormIntervalEntry InvoiceProducts;
        
        /// <summary>
        /// DivPayrollProducts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DivPayrollProducts;
        
        /// <summary>
        /// PayrollProducts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.FormIntervalEntry PayrollProducts;
        
        /// <summary>
        /// DivTimeCodeBreak control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DivTimeCodeBreak;
        
        /// <summary>
        /// StartType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.SelectEntry StartType;
        
        /// <summary>
        /// StartTimeMinutes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.TextEntry StartTimeMinutes;
        
        /// <summary>
        /// TimeCodeEarlierThanStart control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.SelectEntry TimeCodeEarlierThanStart;
        
        /// <summary>
        /// StopType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.SelectEntry StopType;
        
        /// <summary>
        /// StopTimeMinutes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.TextEntry StopTimeMinutes;
        
        /// <summary>
        /// TimeCodeLaterThanStop control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.SelectEntry TimeCodeLaterThanStop;
        
        /// <summary>
        /// MinMinutes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.TextEntry MinMinutes;
        
        /// <summary>
        /// MaxMinutes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.TextEntry MaxMinutes;
        
        /// <summary>
        /// DefaultMinutes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.TextEntry DefaultMinutes;
        
        /// <summary>
        /// StartTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.TextEntry StartTime;
        
        /// <summary>
        /// TimeCodeMoreThanMax control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.SelectEntry TimeCodeMoreThanMax;
        
        /// <summary>
        /// TimeCodeBetweenStdAndMax control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.SelectEntry TimeCodeBetweenStdAndMax;
        
        /// <summary>
        /// TimeCodeStd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.SelectEntry TimeCodeStd;
        
        /// <summary>
        /// TimeCodeBetweenMinAndStd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.SelectEntry TimeCodeBetweenMinAndStd;
        
        /// <summary>
        /// TimeCodeLessThanMin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.SelectEntry TimeCodeLessThanMin;
        
        /// <summary>
        /// DivTimeCodeBreakGroup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DivTimeCodeBreakGroup;
        
        /// <summary>
        /// TimeCodeBreakEmployeeGroups control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.FormIntervalEntry TimeCodeBreakEmployeeGroups;
        
        /// <summary>
        /// TimeCodeBreakGroup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.SelectEntry TimeCodeBreakGroup;
    }
}
