using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using Newtonsoft.Json;
using SoftOne.Soe.Business.Core.PaymentIO.SEPAV3;
using SoftOne.Soe.Common.DTO;
using SoftOne.Soe.Common.Util;
using SoftOne.Soe.Data;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace SoftOne.Soe.Business.Core.Tests
{
    /// <summary>
    /// Tests for SEPAV3Manager.
    /// Test data for Camt54_* cases is generated by Soe.TestDataGenerator.Scripts.ConvertSupplierStreamToEntity.
    /// </summary>
    [TestClass]
    public class SEPAV3ManagerTests
    {
        public TestContext TestContext { get; set; }

        private static string TestDataPath => Path.Combine(Path.GetDirectoryName(typeof(SEPAV3ManagerTests).Assembly.Location), "TestData", "SEPAV3");

        [TestMethod]
        public void ConvertSupplierStreamToEntity_TestCase_MatchingPayment() => RunTestCase("TestCase_MatchingPayment");

        [TestMethod]
        public void ConvertSupplierStreamToEntity_TestCase_NoMatch() => RunTestCase("TestCase_NoMatch");

        [TestMethod]
        public void ConvertSupplierStreamToEntity_Camt54_1() => RunTestCase("Camt54_1");

        [TestMethod]
        public void ConvertSupplierStreamToEntity_Camt54_2() => RunTestCase("Camt54_2");

        [TestMethod]
        public void ConvertSupplierStreamToEntity_Camt54_3() => RunTestCase("Camt54_3");

        private void RunTestCase(string testCaseName)
        {
            var (input, mockData, expected) = LoadTestCase(testCaseName);
            var mockDataAccess = SetupMockDataAccess(mockData, input.ActorCompanyId);
            var sepaManager = new SEPAV3Manager(null);
            var logText = new List<string>();

            var xmlContent = LoadXmlContent(testCaseName, input.XmlFile);
            var files = sepaManager.ParseCAMTFile(xmlContent, ParseImportType(input.ImportType));

            var conversionResult = sepaManager.ConvertSupplierStreamToEntity(
                files: files,
                actorCompanyId: input.ActorCompanyId,
                paymentOriginType: ParseOriginType(input.PaymentOriginType),
                logText: ref logText,
                paymentImportId: input.PaymentImportId,
                batchId: input.BatchId,
                importType: ParseImportType(input.ImportType),
                dataAccess: mockDataAccess.Object,
                warningLogger: msg => logText.Add($"[WARNING] {msg}"));

            OutputWarnings(testCaseName, logText);
            AssertConversionResult(expected, conversionResult);
        }

        private void OutputWarnings(string testCaseName, List<string> logText)
        {
            var warnings = logText.Where(msg => msg.StartsWith("[WARNING]")).ToList();
            if (warnings.Any())
            {
                TestContext.WriteLine($"=== Warnings for {testCaseName} ===");
                foreach (var msg in warnings)
                    TestContext.WriteLine(msg);
                TestContext.WriteLine("=== End warnings ===");
            }
        }

        private static void AssertConversionResult(SEPAV3TestExpected expected, ConvertSupplierStreamResult conversionResult)
        {
            Assert.AreEqual(expected.Success, conversionResult.Result.Success,
                $"Expected Success={expected.Success} but got {conversionResult.Result.Success}. Error: {conversionResult.Result.ErrorMessage}");

            var actualImports = conversionResult.PaymentImports;
            Assert.IsNotNull(actualImports, "PaymentImports should not be null");
            Assert.AreEqual(expected.PaymentImports.Count, actualImports.Count,
                $"Expected {expected.PaymentImports.Count} imports but got {actualImports.Count}. " +
                $"Actual InvoiceNrs: [{string.Join(", ", actualImports.Select(i => i.InvoiceNr))}]");

            for (int i = 0; i < expected.PaymentImports.Count; i++)
            {
                var exp = expected.PaymentImports[i];
                var act = actualImports[i];
                var context = $"Import[{i}] InvoiceNr='{act.InvoiceNr}' Customer='{act.Customer}'";

                Assert.AreEqual(exp.Status, act.Status, $"{context}: Status mismatch");
                Assert.AreEqual(exp.State, act.State, $"{context}: State mismatch");
                Assert.AreEqual(exp.InvoiceId, act.InvoiceId, $"{context}: InvoiceId mismatch");
                Assert.AreEqual(exp.InvoiceNr, act.InvoiceNr, $"{context}: InvoiceNr mismatch");
                Assert.AreEqual(exp.CustomerId, act.CustomerId, $"{context}: CustomerId mismatch");
                Assert.AreEqual(exp.Customer, act.Customer, $"{context}: Customer mismatch");
                Assert.AreEqual(exp.PaidAmount, act.PaidAmount, $"{context}: PaidAmount mismatch");
                Assert.AreEqual(exp.InvoiceAmount, act.InvoiceAmount, $"{context}: InvoiceAmount mismatch");
            }
        }

        private static (SEPAV3TestInput input, SEPAV3TestMockData mockData, SEPAV3TestExpected expected) LoadTestCase(string testCaseName)
        {
            var testCasePath = Path.Combine(TestDataPath, testCaseName);
            return (
                JsonConvert.DeserializeObject<SEPAV3TestInput>(File.ReadAllText(Path.Combine(testCasePath, "input.json"))),
                JsonConvert.DeserializeObject<SEPAV3TestMockData>(File.ReadAllText(Path.Combine(testCasePath, "mockdata.json"))),
                JsonConvert.DeserializeObject<SEPAV3TestExpected>(File.ReadAllText(Path.Combine(testCasePath, "expected.json")))
            );
        }

        private static string LoadXmlContent(string testCaseName, string xmlFile)
        {
            var xmlPath = Path.Combine(TestDataPath, testCaseName, xmlFile);
            return File.ReadAllText(xmlPath);
        }

        private static Mock<ISupplierPaymentDataAccess> SetupMockDataAccess(SEPAV3TestMockData mockData, int actorCompanyId)
        {
            var mock = new Mock<ISupplierPaymentDataAccess>();

            foreach (var row in mockData.PaymentRows)
            {
                mock.Setup(x => x.GetPaymentRowWithSupplierInvoice(row.PaymentRowId, actorCompanyId))
                    .Returns(ToPaymentRowInvoiceDTO(row));
            }

            var byPaymentId = mockData.PaymentRows.GroupBy(r => r.PaymentId);
            foreach (var group in byPaymentId)
            {
                var dtos = group.Select(ToPaymentRowInvoiceDTO).ToList();
                mock.Setup(x => x.GetPaymentRowsWithSupplierInvoice(group.Key, actorCompanyId))
                    .Returns(dtos);

                foreach (var billingType in Enum.GetValues(typeof(TermGroup_BillingType)).Cast<TermGroup_BillingType>())
                {
                    var filtered = dtos.Where(d => d.BillingType == (int)billingType).ToList();
                    foreach (var actorId in dtos.Select(d => d.InvoiceActorId).Distinct())
                    {
                        var actorFiltered = filtered.Where(d => d.InvoiceActorId == actorId).ToList();
                        mock.Setup(x => x.GetPaymentRowsWithSupplierInvoice(group.Key, actorCompanyId, actorId, billingType))
                            .Returns(actorFiltered);
                    }
                }
            }

            mock.Setup(x => x.GetAutoTransferAutogiroSetting())
                .Returns(mockData.Settings?.AutoTransferAutogiro ?? false);

            return mock;
        }

        private static PaymentRowInvoiceDTO ToPaymentRowInvoiceDTO(SEPAV3TestPaymentRow row)
        {
            return new PaymentRowInvoiceDTO
            {
                PaymentRowId = row.PaymentRowId,
                PaymentId = row.PaymentId,
                InvoiceId = row.InvoiceId,
                InvoiceNr = row.InvoiceNr,
                InvoiceTotalAmount = row.InvoiceTotalAmount,
                InvoicePaidAmount = row.InvoicePaidAmount,
                FullyPayed = row.FullyPayed,
                Status = row.Status,
                InvoiceActorId = row.InvoiceActorId,
                InvoiceActorName = row.InvoiceActorName,
                BillingType = row.BillingType,
                Amount = row.Amount,
                AmountCurrency = row.AmountCurrency,
                InvoiceDate = row.InvoiceDate,
                InvoiceDueDate = row.InvoiceDueDate,
                PayDate = row.PayDate,
                PaymentNr = row.PaymentNr,
                InvoiceSeqNr = row.InvoiceSeqNr,
                SysPaymentTypeId = row.SysPaymentTypeId
            };
        }

        private static SoeOriginType ParseOriginType(string value) => value switch
        {
            "SupplierPayment" => SoeOriginType.SupplierPayment,
            "CustomerPayment" => SoeOriginType.CustomerPayment,
            _ => throw new ArgumentException($"Unknown origin type: {value}")
        };

        private static ImportPaymentType ParseImportType(string value) => value switch
        {
            "SupplierPayment" => ImportPaymentType.SupplierPayment,
            "CustomerPayment" => ImportPaymentType.CustomerPayment,
            _ => throw new ArgumentException($"Unknown import type: {value}")
        };
    }
}
