//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
    [System.SerializableAttribute()]
    public partial class AltinnFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnExtendedErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnLocalizedErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnErrorMessage {
            get {
                return this.AltinnErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnErrorMessageField, value) != true)) {
                    this.AltinnErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnExtendedErrorMessage {
            get {
                return this.AltinnExtendedErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnExtendedErrorMessageField, value) != true)) {
                    this.AltinnExtendedErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnExtendedErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnLocalizedErrorMessage {
            get {
                return this.AltinnLocalizedErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnLocalizedErrorMessageField, value) != true)) {
                    this.AltinnLocalizedErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnLocalizedErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorGuid {
            get {
                return this.ErrorGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorGuidField, value) != true)) {
                    this.ErrorGuidField = value;
                    this.RaisePropertyChanged("ErrorGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorID {
            get {
                return this.ErrorIDField;
            }
            set {
                if ((this.ErrorIDField.Equals(value) != true)) {
                    this.ErrorIDField = value;
                    this.RaisePropertyChanged("ErrorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserGuid {
            get {
                return this.UserGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.UserGuidField, value) != true)) {
                    this.UserGuidField = value;
                    this.RaisePropertyChanged("UserGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormTaskShipmentBE", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    [System.SerializableAttribute()]
    public partial class FormTaskShipmentBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReporteeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalShipmentReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.FormTask FormTasksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.Attachment[] AttachmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.Signature SignaturesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsUserDelegationLockedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserDefinedNumberOfSignaturesRequiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.DelegatedUserBE[] UsersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.EncryptedKeyBE EncryptedKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CaseIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Reportee {
            get {
                return this.ReporteeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReporteeField, value) != true)) {
                    this.ReporteeField = value;
                    this.RaisePropertyChanged("Reportee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ExternalShipmentReference {
            get {
                return this.ExternalShipmentReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalShipmentReferenceField, value) != true)) {
                    this.ExternalShipmentReferenceField = value;
                    this.RaisePropertyChanged("ExternalShipmentReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.FormTask FormTasks {
            get {
                return this.FormTasksField;
            }
            set {
                if ((object.ReferenceEquals(this.FormTasksField, value) != true)) {
                    this.FormTasksField = value;
                    this.RaisePropertyChanged("FormTasks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.Attachment[] Attachments {
            get {
                return this.AttachmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentsField, value) != true)) {
                    this.AttachmentsField = value;
                    this.RaisePropertyChanged("Attachments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.Signature Signatures {
            get {
                return this.SignaturesField;
            }
            set {
                if ((object.ReferenceEquals(this.SignaturesField, value) != true)) {
                    this.SignaturesField = value;
                    this.RaisePropertyChanged("Signatures");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool IsUserDelegationLocked {
            get {
                return this.IsUserDelegationLockedField;
            }
            set {
                if ((this.IsUserDelegationLockedField.Equals(value) != true)) {
                    this.IsUserDelegationLockedField = value;
                    this.RaisePropertyChanged("IsUserDelegationLocked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int UserDefinedNumberOfSignaturesRequired {
            get {
                return this.UserDefinedNumberOfSignaturesRequiredField;
            }
            set {
                if ((this.UserDefinedNumberOfSignaturesRequiredField.Equals(value) != true)) {
                    this.UserDefinedNumberOfSignaturesRequiredField = value;
                    this.RaisePropertyChanged("UserDefinedNumberOfSignaturesRequired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.DelegatedUserBE[] Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.EncryptedKeyBE EncryptedKey {
            get {
                return this.EncryptedKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EncryptedKeyField, value) != true)) {
                    this.EncryptedKeyField = value;
                    this.RaisePropertyChanged("EncryptedKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.Nullable<int> CaseID {
            get {
                return this.CaseIDField;
            }
            set {
                if ((this.CaseIDField.Equals(value) != true)) {
                    this.CaseIDField = value;
                    this.RaisePropertyChanged("CaseID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormTask", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    [System.SerializableAttribute()]
    public partial class FormTask : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ServiceEditionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.Form[] FormsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ServiceCode {
            get {
                return this.ServiceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceCodeField, value) != true)) {
                    this.ServiceCodeField = value;
                    this.RaisePropertyChanged("ServiceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ServiceEdition {
            get {
                return this.ServiceEditionField;
            }
            set {
                if ((this.ServiceEditionField.Equals(value) != true)) {
                    this.ServiceEditionField = value;
                    this.RaisePropertyChanged("ServiceEdition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.Form[] Forms {
            get {
                return this.FormsField;
            }
            set {
                if ((object.ReferenceEquals(this.FormsField, value) != true)) {
                    this.FormsField = value;
                    this.RaisePropertyChanged("Forms");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Signature", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    [System.SerializableAttribute()]
    public partial class Signature : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndUserSystemReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndUserSystemUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndUserSystemLoginDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndUserSystemSignatureDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndUserSystemVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndUserSystemSignatureLogIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EndUserSystemReference {
            get {
                return this.EndUserSystemReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.EndUserSystemReferenceField, value) != true)) {
                    this.EndUserSystemReferenceField = value;
                    this.RaisePropertyChanged("EndUserSystemReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EndUserSystemUserId {
            get {
                return this.EndUserSystemUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EndUserSystemUserIdField, value) != true)) {
                    this.EndUserSystemUserIdField = value;
                    this.RaisePropertyChanged("EndUserSystemUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime EndUserSystemLoginDateTime {
            get {
                return this.EndUserSystemLoginDateTimeField;
            }
            set {
                if ((this.EndUserSystemLoginDateTimeField.Equals(value) != true)) {
                    this.EndUserSystemLoginDateTimeField = value;
                    this.RaisePropertyChanged("EndUserSystemLoginDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime EndUserSystemSignatureDateTime {
            get {
                return this.EndUserSystemSignatureDateTimeField;
            }
            set {
                if ((this.EndUserSystemSignatureDateTimeField.Equals(value) != true)) {
                    this.EndUserSystemSignatureDateTimeField = value;
                    this.RaisePropertyChanged("EndUserSystemSignatureDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string EndUserSystemVersion {
            get {
                return this.EndUserSystemVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.EndUserSystemVersionField, value) != true)) {
                    this.EndUserSystemVersionField = value;
                    this.RaisePropertyChanged("EndUserSystemVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string EndUserSystemSignatureLogId {
            get {
                return this.EndUserSystemSignatureLogIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EndUserSystemSignatureLogIdField, value) != true)) {
                    this.EndUserSystemSignatureLogIdField = value;
                    this.RaisePropertyChanged("EndUserSystemSignatureLogId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EncryptedKeyBE", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    [System.SerializableAttribute()]
    public partial class EncryptedKeyBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.ReporteeSymmetricKeyBE ReporteeSymmetricKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.ServiceOwnerSymmetricKeyBE[] ServiceOwnerSymmetricKeysField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.ReporteeSymmetricKeyBE ReporteeSymmetricKey {
            get {
                return this.ReporteeSymmetricKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ReporteeSymmetricKeyField, value) != true)) {
                    this.ReporteeSymmetricKeyField = value;
                    this.RaisePropertyChanged("ReporteeSymmetricKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.ServiceOwnerSymmetricKeyBE[] ServiceOwnerSymmetricKeys {
            get {
                return this.ServiceOwnerSymmetricKeysField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOwnerSymmetricKeysField, value) != true)) {
                    this.ServiceOwnerSymmetricKeysField = value;
                    this.RaisePropertyChanged("ServiceOwnerSymmetricKeys");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Attachment", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    [System.SerializableAttribute()]
    public partial class Attachment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndUserSystemReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EncryptedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] AttachementDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EndUserSystemReference {
            get {
                return this.EndUserSystemReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.EndUserSystemReferenceField, value) != true)) {
                    this.EndUserSystemReferenceField = value;
                    this.RaisePropertyChanged("EndUserSystemReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ParentReference {
            get {
                return this.ParentReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentReferenceField, value) != true)) {
                    this.ParentReferenceField = value;
                    this.RaisePropertyChanged("ParentReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool Encrypted {
            get {
                return this.EncryptedField;
            }
            set {
                if ((this.EncryptedField.Equals(value) != true)) {
                    this.EncryptedField = value;
                    this.RaisePropertyChanged("Encrypted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public byte[] AttachementData {
            get {
                return this.AttachementDataField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachementDataField, value) != true)) {
                    this.AttachementDataField = value;
                    this.RaisePropertyChanged("AttachementData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DelegatedUserBE", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    [System.SerializableAttribute()]
    public partial class DelegatedUserBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SSNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint NumberOfSignaturesAllowedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SSN {
            get {
                return this.SSNField;
            }
            set {
                if ((object.ReferenceEquals(this.SSNField, value) != true)) {
                    this.SSNField = value;
                    this.RaisePropertyChanged("SSN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public uint NumberOfSignaturesAllowed {
            get {
                return this.NumberOfSignaturesAllowedField;
            }
            set {
                if ((this.NumberOfSignaturesAllowedField.Equals(value) != true)) {
                    this.NumberOfSignaturesAllowedField = value;
                    this.RaisePropertyChanged("NumberOfSignaturesAllowed");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Form", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    [System.SerializableAttribute()]
    public partial class Form : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CompletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataFormatIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DataFormatVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndUserSystemReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Completed {
            get {
                return this.CompletedField;
            }
            set {
                if ((this.CompletedField.Equals(value) != true)) {
                    this.CompletedField = value;
                    this.RaisePropertyChanged("Completed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DataFormatId {
            get {
                return this.DataFormatIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DataFormatIdField, value) != true)) {
                    this.DataFormatIdField = value;
                    this.RaisePropertyChanged("DataFormatId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DataFormatVersion {
            get {
                return this.DataFormatVersionField;
            }
            set {
                if ((this.DataFormatVersionField.Equals(value) != true)) {
                    this.DataFormatVersionField = value;
                    this.RaisePropertyChanged("DataFormatVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EndUserSystemReference {
            get {
                return this.EndUserSystemReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.EndUserSystemReferenceField, value) != true)) {
                    this.EndUserSystemReferenceField = value;
                    this.RaisePropertyChanged("EndUserSystemReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentReference {
            get {
                return this.ParentReferenceField;
            }
            set {
                if ((this.ParentReferenceField.Equals(value) != true)) {
                    this.ParentReferenceField = value;
                    this.RaisePropertyChanged("ParentReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string FormData {
            get {
                return this.FormDataField;
            }
            set {
                if ((object.ReferenceEquals(this.FormDataField, value) != true)) {
                    this.FormDataField = value;
                    this.RaisePropertyChanged("FormData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReporteeSymmetricKeyBE", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    [System.SerializableAttribute()]
    public partial class ReporteeSymmetricKeyBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReporteeIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReporteeId {
            get {
                return this.ReporteeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ReporteeIdField, value) != true)) {
                    this.ReporteeIdField = value;
                    this.RaisePropertyChanged("ReporteeId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceOwnerSymmetricKeyBE", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    [System.SerializableAttribute()]
    public partial class ServiceOwnerSymmetricKeyBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceOwnerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CertificateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ServiceOwnerCode {
            get {
                return this.ServiceOwnerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOwnerCodeField, value) != true)) {
                    this.ServiceOwnerCodeField = value;
                    this.RaisePropertyChanged("ServiceOwnerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int CertificateId {
            get {
                return this.CertificateIdField;
            }
            set {
                if ((this.CertificateIdField.Equals(value) != true)) {
                    this.CertificateIdField = value;
                    this.RaisePropertyChanged("CertificateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiptExternalBE", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    [System.SerializableAttribute()]
    public partial class ReceiptExternalBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReceiptIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiptTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiptHistoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastChangedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.ReceiptType ReceiptTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.ReceiptStatus ReceiptStatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentReceiptIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.ReferenceBE[] ReferencesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.ReceiptExternalBE[] SubReceiptsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReceiptId {
            get {
                return this.ReceiptIdField;
            }
            set {
                if ((this.ReceiptIdField.Equals(value) != true)) {
                    this.ReceiptIdField = value;
                    this.RaisePropertyChanged("ReceiptId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReceiptText {
            get {
                return this.ReceiptTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiptTextField, value) != true)) {
                    this.ReceiptTextField = value;
                    this.RaisePropertyChanged("ReceiptText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ReceiptHistory {
            get {
                return this.ReceiptHistoryField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiptHistoryField, value) != true)) {
                    this.ReceiptHistoryField = value;
                    this.RaisePropertyChanged("ReceiptHistory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime LastChanged {
            get {
                return this.LastChangedField;
            }
            set {
                if ((this.LastChangedField.Equals(value) != true)) {
                    this.LastChangedField = value;
                    this.RaisePropertyChanged("LastChanged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.ReceiptType ReceiptTypeName {
            get {
                return this.ReceiptTypeNameField;
            }
            set {
                if ((this.ReceiptTypeNameField.Equals(value) != true)) {
                    this.ReceiptTypeNameField = value;
                    this.RaisePropertyChanged("ReceiptTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.ReceiptStatus ReceiptStatusCode {
            get {
                return this.ReceiptStatusCodeField;
            }
            set {
                if ((this.ReceiptStatusCodeField.Equals(value) != true)) {
                    this.ReceiptStatusCodeField = value;
                    this.RaisePropertyChanged("ReceiptStatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int ParentReceiptId {
            get {
                return this.ParentReceiptIdField;
            }
            set {
                if ((this.ParentReceiptIdField.Equals(value) != true)) {
                    this.ParentReceiptIdField = value;
                    this.RaisePropertyChanged("ParentReceiptId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.ReferenceBE[] References {
            get {
                return this.ReferencesField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferencesField, value) != true)) {
                    this.ReferencesField = value;
                    this.RaisePropertyChanged("References");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.ReceiptExternalBE[] SubReceipts {
            get {
                return this.SubReceiptsField;
            }
            set {
                if ((object.ReferenceEquals(this.SubReceiptsField, value) != true)) {
                    this.SubReceiptsField = value;
                    this.RaisePropertyChanged("SubReceipts");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiptType", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    public enum ReceiptType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FormTask = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Correspondence = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PINCODE = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Subscription = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Outbound = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PreFill = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDLS = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSF = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterER = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFProperty = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFStreet = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFCountry = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFUser = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LookUp = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFStreetAdd = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFPropertyAdd = 16,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiptStatus", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    public enum ReceiptStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnExpectedError = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValidationFailed = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReferenceBE", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    [System.SerializableAttribute()]
    public partial class ReferenceBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.ReferenceType ReferenceTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReporteeIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReferenceValue {
            get {
                return this.ReferenceValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceValueField, value) != true)) {
                    this.ReferenceValueField = value;
                    this.RaisePropertyChanged("ReferenceValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.ReferenceType ReferenceTypeName {
            get {
                return this.ReferenceTypeNameField;
            }
            set {
                if ((this.ReferenceTypeNameField.Equals(value) != true)) {
                    this.ReferenceTypeNameField = value;
                    this.RaisePropertyChanged("ReferenceTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int ReporteeID {
            get {
                return this.ReporteeIDField;
            }
            set {
                if ((this.ReporteeIDField.Equals(value) != true)) {
                    this.ReporteeIDField = value;
                    this.RaisePropertyChanged("ReporteeID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReferenceType", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    public enum ReferenceType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExternalShipmentReference = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EndUserSystemReference = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ParentReference = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SendersReference = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WorkFlowReference = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BatchReference = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OutboundShipmentReference = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReceiversReference = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Altinn1Reference = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OwnerPartyReference = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartyReference = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArchiveReference = 12,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10", ConfigurationName="Altinn.IntermediaryInboundBasic.IIntermediaryInboundExternalBasic")]
    public interface IIntermediaryInboundExternalBasic {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test", ReplyAction="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.AltinnFault), Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.TestResponse Test(SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10/I" +
            "IntermediaryInboundExternalBasic/GetAltinnSubmissionStatusBasic", ReplyAction="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10/I" +
            "IntermediaryInboundExternalBasic/GetAltinnSubmissionStatusBasicResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.AltinnFault), Action="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10/I" +
            "IntermediaryInboundExternalBasic/GetAltinnSubmissionStatusBasicAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.GetAltinnSubmissionStatusBasicResponse GetAltinnSubmissionStatusBasic(SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.GetAltinnSubmissionStatusBasicRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10/I" +
            "IntermediaryInboundExternalBasic/SubmitFormTaskBasic", ReplyAction="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10/I" +
            "IntermediaryInboundExternalBasic/SubmitFormTaskBasicResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.AltinnFault), Action="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10/I" +
            "IntermediaryInboundExternalBasic/SubmitFormTaskBasicAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.SubmitFormTaskBasicResponse SubmitFormTaskBasic(SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.SubmitFormTaskBasicRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestRequest {
        
        public TestRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestResponse", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestResponse {
        
        public TestResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAltinnSubmissionStatusBasic", WrapperNamespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10", IsWrapped=true)]
    public partial class GetAltinnSubmissionStatusBasicRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10", Order=0)]
        public string systemUserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10", Order=1)]
        public string systemPassword;
        
        public GetAltinnSubmissionStatusBasicRequest() {
        }
        
        public GetAltinnSubmissionStatusBasicRequest(string systemUserName, string systemPassword) {
            this.systemUserName = systemUserName;
            this.systemPassword = systemPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAltinnSubmissionStatusBasicResponse", WrapperNamespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10", IsWrapped=true)]
    public partial class GetAltinnSubmissionStatusBasicResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10", Order=0)]
        public int GetAltinnSubmissionStatusBasicResult;
        
        public GetAltinnSubmissionStatusBasicResponse() {
        }
        
        public GetAltinnSubmissionStatusBasicResponse(int GetAltinnSubmissionStatusBasicResult) {
            this.GetAltinnSubmissionStatusBasicResult = GetAltinnSubmissionStatusBasicResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitFormTaskBasicRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitFormTaskBasic", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10", Order=0)]
        public SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.SubmitFormTaskBasicRequestBody Body;
        
        public SubmitFormTaskBasicRequest() {
        }
        
        public SubmitFormTaskBasicRequest(SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.SubmitFormTaskBasicRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    public partial class SubmitFormTaskBasicRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string systemUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string systemPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userSSN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string userPinCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string authMethod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.FormTaskShipmentBE formTaskShipment;
        
        public SubmitFormTaskBasicRequestBody() {
        }
        
        public SubmitFormTaskBasicRequestBody(string systemUserName, string systemPassword, string userSSN, string userPassword, string userPinCode, string authMethod, SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.FormTaskShipmentBE formTaskShipment) {
            this.systemUserName = systemUserName;
            this.systemPassword = systemPassword;
            this.userSSN = userSSN;
            this.userPassword = userPassword;
            this.userPinCode = userPinCode;
            this.authMethod = authMethod;
            this.formTaskShipment = formTaskShipment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitFormTaskBasicResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitFormTaskBasicResponse", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10", Order=0)]
        public SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.SubmitFormTaskBasicResponseBody Body;
        
        public SubmitFormTaskBasicResponse() {
        }
        
        public SubmitFormTaskBasicResponse(SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.SubmitFormTaskBasicResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    public partial class SubmitFormTaskBasicResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.ReceiptExternalBE SubmitFormTaskBasicResult;
        
        public SubmitFormTaskBasicResponseBody() {
        }
        
        public SubmitFormTaskBasicResponseBody(SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.ReceiptExternalBE SubmitFormTaskBasicResult) {
            this.SubmitFormTaskBasicResult = SubmitFormTaskBasicResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIntermediaryInboundExternalBasicChannel : SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.IIntermediaryInboundExternalBasic, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntermediaryInboundExternalBasicClient : System.ServiceModel.ClientBase<SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.IIntermediaryInboundExternalBasic>, SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.IIntermediaryInboundExternalBasic {
        
        public IntermediaryInboundExternalBasicClient() {
        }
        
        public IntermediaryInboundExternalBasicClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntermediaryInboundExternalBasicClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntermediaryInboundExternalBasicClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntermediaryInboundExternalBasicClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.TestResponse Test(SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        public SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.GetAltinnSubmissionStatusBasicResponse GetAltinnSubmissionStatusBasic(SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.GetAltinnSubmissionStatusBasicRequest request) {
            return base.Channel.GetAltinnSubmissionStatusBasic(request);
        }
        
        public SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.SubmitFormTaskBasicResponse SubmitFormTaskBasic(SoftOne.Soe.Business.Altinn.IntermediaryInboundBasic.SubmitFormTaskBasicRequest request) {
            return base.Channel.SubmitFormTaskBasic(request);
        }
    }
}
