//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftOne.Soe.Web.soe.common.attest.state {
    
    
    public partial class _default {
        
        /// <summary>
        /// Form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.Form Form1;
        
        /// <summary>
        /// Entity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.SelectEntry Entity;
        
        /// <summary>
        /// Name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.TextEntry Name;
        
        /// <summary>
        /// Description control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.TextEntry Description;
        
        /// <summary>
        /// Sort control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.NumericEntry Sort;
        
        /// <summary>
        /// Initial control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.CheckBoxEntry Initial;
        
        /// <summary>
        /// InitialInstruction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.Instruction InitialInstruction;
        
        /// <summary>
        /// Closed control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.CheckBoxEntry Closed;
        
        /// <summary>
        /// Hidden control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.CheckBoxEntry Hidden;
        
        /// <summary>
        /// Locked control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.CheckBoxEntry Locked;
        
        /// <summary>
        /// Color control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.TextEntry Color;
        
        /// <summary>
        /// ImageSource control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.TextEntry ImageSource;
    }
}
