import { test } from '../../fixtures/sales-fixture';
import * as allure from "allure-js-commons";
import { getAccountExValue } from '../../../utils/properties';
import { CustomerUtil } from '../../../apis/utils/CustomerUtil';
import { AgreementUtil } from '../../../apis/utils/AgreementUtil';
import { ProductUtils } from '../../../apis/utils/ProductUtil';

let testCaseId: string = '78498';
let envUrl: string;
let customerUtil: CustomerUtil;
let customers: any;
let agreementUtil: AgreementUtil;
let groups: any;
let productUtil: ProductUtils;
let products: any;
let internalText_1: string;
let internalText_2: string;
let internalText_3: string;

test.use({ account: { domain: process.env.defualt_domain!, user: 'adminERP' } });

test.beforeEach(async ({ page, accountEx, salesBasePage }) => {
    await allure.parentSuite("Sales");
    await allure.suite("Agreements");
    await allure.subSuite("Agreement");
    await allure.link('https://dev.azure.com/softonedev/XE/_workitems/edit/' + testCaseId, "Test case : " + testCaseId);
    envUrl = accountEx.baseUrl;
    await salesBasePage.SetupSales(envUrl, getAccountExValue(accountEx, 'role')?.toString() ?? 'Admin');
    customerUtil = new CustomerUtil(page, envUrl);
    customers = await customerUtil.getCustomers();
    agreementUtil = new AgreementUtil(page, envUrl);
    groups = await agreementUtil.getAgreementGroups();
    productUtil = new ProductUtils(page, envUrl);
    products = await productUtil.getProducts();
    internalText_1 = 'Agreement_' + testCaseId + Math.floor(100000 + Math.random() * 900000) + '_1';
    internalText_2 = 'Agreement_' + testCaseId + Math.floor(100000 + Math.random() * 900000) + '_2';
    internalText_3 = 'Agreement_' + testCaseId + Math.floor(100000 + Math.random() * 900000) + '_3';
    await agreementUtil.createAgreement(groups[0].contractGroupId, customers[0].actorCustomerId, products[0].productId, internalText_1);
    await agreementUtil.createAgreement(groups[0].contractGroupId, customers[0].actorCustomerId, products[0].productId, internalText_2);
    await agreementUtil.createAgreement(groups[0].contractGroupId, customers[0].actorCustomerId, products[0].productId, internalText_3);
});

test(testCaseId + ': Create Agreement To Order : AP ', { tag: ['@Sales', '@Agreements', '@Regression'] }, async ({ salesBasePage, agreementsPage, orderPageJS }) => {
    await salesBasePage.goToMenu('Agreements ', 'Agreements');
    await agreementsPage.waitForPageLoad();
    await agreementsPage.moveToAgreementTab();
    await agreementsPage.filterByInternalTextAgreements(internalText_1);
    await agreementsPage.editAgreement();
    await agreementsPage.trasnferToOrder();
    await salesBasePage.goToMenu('Order', 'Order');
    await orderPageJS.waitForPageLoad();
    await orderPageJS.Reload();
    await orderPageJS.filterByInternalText(internalText_1);
    await orderPageJS.verifyOrder();
    await orderPageJS.verifyStatus('Documentation');
    await salesBasePage.goToMenu('Agreements ', 'Agreements');
    await agreementsPage.waitForPageLoad();
    await agreementsPage.moveToCurrentAgreementTab();
    await agreementsPage.filterByInternalTextCurrent(internalText_2);
    await agreementsPage.selectAgreement();
    await agreementsPage.filterByInternalTextCurrent(internalText_3);
    await agreementsPage.selectAgreement();
    await agreementsPage.trasnferToOrderfromAgreement();
    await salesBasePage.goToMenu('Order', 'Order');
    await orderPageJS.waitForPageLoad();
    await orderPageJS.filterByInternalText(internalText_2);
    await orderPageJS.verifyOrder();
    await orderPageJS.verifyStatus('Documentation');
    await orderPageJS.filterByInternalText(internalText_3);
    await orderPageJS.verifyOrder();
    await orderPageJS.verifyStatus('Documentation');
});
