import { test } from '../../fixtures/sales-fixture';
import * as allure from "allure-js-commons";
import { getAccountExValue, getEnvironmentValue } from '../../../utils/properties';
import { ManageUtils } from 'apis/utils/ManageUtils';
import { getDateUtil } from '../../../utils/CommonUtil';

let testCaseId: string = '78099';
let envUrl: string;
let customer: string = getEnvironmentValue('default_customer') ?? '';
let employee: string = getEnvironmentValue('default_employee') ?? '';
let internalText: string = `Auto ${Math.random().toString(36).substring(2, 7)} ` + ' ' + testCaseId;

test.use({ account: { domain: process.env.defualt_domain!, user: 'adminERP' } });
test.beforeEach(async ({ accountEx, salesBasePage, page }) => {
    await allure.parentSuite("Sales");
    await allure.suite("Projects");
    await allure.subSuite("Time Report");
    await allure.link('https://dev.azure.com/softonedev/XE/_workitems/edit/' + testCaseId, "Test case : " + testCaseId);
    envUrl = accountEx.baseUrl;
    await salesBasePage.SetupSales(envUrl, getAccountExValue(accountEx, 'role')?.toString() ?? 'Admin');
    await new ManageUtils(page, envUrl).verifyOrderCheckLists();
});

test(testCaseId + ': Verify time search : SR', { tag: ['@Sales', '@Projects', '@TimeReport', '@Regression'] }, async ({ timeReportPage, orderPageJS }) => {
    await orderPageJS.goToMenu('Order', 'Order');
    await orderPageJS.waitForPageLoad();
    await orderPageJS.createItem();
    await orderPageJS.addCustomer(customer);
    await orderPageJS.addInternalText(internalText);
    await orderPageJS.saveOrder();
    const capturedOrderNumber = await orderPageJS.getOrderNumber();
    const capturedProjectNumber = await orderPageJS.getProjectNumber();
    const orderDropdownValue = `${capturedOrderNumber} - ${customer}`;
    const projectDropdownValue = `${capturedProjectNumber} ${customer}`;
    await timeReportPage.goToMenu('Projects', 'Time Report');
    await timeReportPage.clickAddRow();
    await timeReportPage.setRegisterTimeDetails({ employeeName: employee, orderNumber: orderDropdownValue, projectNumber: projectDropdownValue, chargingType: 'Arbetad tid', timeWorked: '5', billableTime: '3', rowIndex: 0 });
    await timeReportPage.saveRegisteredTime();
    await timeReportPage.page.waitForTimeout(2000);
    await timeReportPage.clickAddRow();
    await timeReportPage.setRegisterTimeDetails({ employeeName: employee, orderNumber: capturedOrderNumber, projectNumber: capturedProjectNumber, chargingType: 'Övertid efter kl 24 samt helg', timeWorked: '5', billableTime: '2', rowIndex: 0 });
    await timeReportPage.saveRegisteredTime();
    const today = await getDateUtil(0, false);
    await timeReportPage.setDateFilter(today, today);
    await timeReportPage.applyFilters({ "Order": capturedOrderNumber, "Time Worked": "5", "Billable Time": "3" });
    await timeReportPage.VerifyRowCount(1);
    await timeReportPage.clearAllFilters();
    const sevenDaysForward = await getDateUtil(7, true);
    await timeReportPage.setDateFilter(today, sevenDaysForward);
    await timeReportPage.applyFilters({ "Order": capturedOrderNumber, "Billable Time": "3", "Time Worked": "5" });
    await timeReportPage.VerifyRowCount(1);
    await timeReportPage.clearAllFilters();
    await timeReportPage.setDateFilter(today, today);
    await timeReportPage.setOrderNumberTopFilter(capturedOrderNumber);
    await timeReportPage.clickSearchButton();
    await timeReportPage.VerifyRowCount(2);
    await timeReportPage.setOrderNumberTopFilter(capturedOrderNumber);
    await timeReportPage.clickSearchButton();
    await timeReportPage.applyFilters({ "Time Worked": "5", "Billable Time": "3" });
    await timeReportPage.VerifyRowCount(1);
    await timeReportPage.setProjectNumberTopFilter(capturedProjectNumber);
    await timeReportPage.clickSearchButton();
    await timeReportPage.applyFilters({ "Billable Time": "3", "Time Worked": "5" });
    await timeReportPage.VerifyRowCount(1);
    await timeReportPage.setEmployeeTopFilter(employee);
    await timeReportPage.setProjectNumberTopFilter(capturedProjectNumber);
    await timeReportPage.clickSearchButton();
    await timeReportPage.applyFilters({ "Time Worked": "5", "Billable Time": "3" });
    await timeReportPage.VerifyRowCount(1);
});