//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftOne.Soe.Web.soe.common.excelimport
{


    public partial class _default
    {

        /// <summary>
        /// AngularSpaHost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.UserControls.AngularSpaHost AngularSpaHost;

        /// <summary>
        /// Form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.Form Form1;

        /// <summary>
        /// File control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.FileEntry File;

        /// <summary>
        /// DoNotModifyWithEmpty control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.CheckBoxEntry DoNotModifyWithEmpty;

        /// <summary>
        /// SoeGrid1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftOne.Soe.Web.Controls.Grid SoeGrid1;
    }
}
